table BridgeEscalationsIssue
	lineageTag: a837877c-6542-494c-abd3-2bae69792097

	column issue_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 87b8a4ee-03cf-4536-a7f8-066094e71353
		summarizeBy: none
		sourceColumn: issue_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS","HIDE_FOREIGN_KEYS"]}

	column ticket_id
		dataType: int64
		formatString: 0
		lineageTag: 5e1d600b-c02d-49b6-95bd-931510cd69e2
		summarizeBy: none
		sourceColumn: ticket_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS","HIDE_FOREIGN_KEYS"]}

	column team_id
		dataType: string
		isHidden
		lineageTag: 88cf56e9-c184-4294-aa7b-9ce9674d50d5
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column squad_id
		dataType: string
		isHidden
		lineageTag: a2f6a125-47e8-4168-9c8e-06a6751c5eea
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column parent_account_id
		dataType: string
		isHidden
		lineageTag: 4bb9bf2d-7405-4dc9-abf8-d22badd711d1
		summarizeBy: none
		sourceColumn: parent_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column standardized_category_id
		dataType: string
		lineageTag: 0d10ab3e-88c1-4f36-b056-746ad78f4982
		summarizeBy: none
		sourceColumn: standardized_category_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column salesforce_account_id
		dataType: string
		isHidden
		lineageTag: 9d886d66-9f82-41fc-b2ba-e9bbbed50778
		summarizeBy: none
		sourceColumn: salesforce_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column region_id
		dataType: string
		isHidden
		lineageTag: ec3b5463-9437-424b-bd8f-ca4549470214
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column 'created month' = Format(BridgeEscalationsIssue[Ticket Created Date], "MM-YYYY")
		lineageTag: a937e62b-ad45-49bd-ba69-bae97de3e034
		summarizeBy: none

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","MONTH_(AS_A_STRING)_MUST_BE_SORTED","FIRST_LETTER_OF_OBJECTS_MUST_BE_CAPITALIZED"]}

	column escalation_month
		dataType: dateTime
		formatString: General Date
		lineageTag: 5fbe4a05-55a0-4eea-a83c-634491876499
		summarizeBy: none
		sourceColumn: escalation_month

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","MONTHCOLUMN_FORMATSTRING","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column 'issue created date'
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: 91fd4eb9-efed-4e76-8f71-afb183b51a67
		summarizeBy: none
		sourceColumn: issue created date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Ticket Created Date'
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: 98224931-79ab-4ece-9484-384498ac4dad
		summarizeBy: none
		sourceColumn: Ticket Created Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Ticket Solved Date'
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: a25cc160-2536-442a-94c9-38b5eab86293
		summarizeBy: none
		sourceColumn: Ticket Solved Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Same month Escalation'
		dataType: int64
		formatString: 0
		lineageTag: 1f8a6f09-c2b3-43c5-97f1-b4658ec45215
		summarizeBy: sum
		sourceColumn: Same month Escalation

		annotation SummarizationSetBy = Automatic

	column 'Escalation Mapping'
		dataType: string
		lineageTag: 07947003-ca3b-4067-8cc6-0121f57e3013
		summarizeBy: none
		sourceColumn: Escalation Mapping

		annotation SummarizationSetBy = Automatic

	partition BridgeEscalationsIssue = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let BridgeEscalationsIssue = #(lf)    supportv3_escalations_issue_bridge#(lf)    | where is_ticket_within_two_years == 1#(lf)    | extend #(lf)        issue_month = startofmonth(issue_created_at),#(lf)        ticket_month = startofmonth(ticket_created_date)#(lf)    | extend #(lf)        ['Same month Escalation'] = case(#(lf)            issue_month == ticket_month, 1,#(lf)            issue_month < ticket_month, 2,#(lf)            0#(lf)        )#(lf)    | extend #(lf)        escalation_month = case(#(lf)             ['Same month Escalation']  == 1, ticket_created_date,#(lf)             ['Same month Escalation']  == 2, issue_created_at,#(lf)            issue_created_at#(lf)        )#(lf)    | project#(lf)        issue_id,#(lf)        ticket_id,#(lf)        ['issue created date'] = issue_created_at,#(lf)        ['Ticket Created Date'] = ticket_created_date,#(lf)        ['Ticket Solved Date'] = ticket_solved_date,#(lf)        team_id,#(lf)        squad_id,#(lf)        parent_account_id,#(lf)        salesforce_account_id,#(lf)        standardized_category_id,#(lf)        region_id,#(lf)         ['Same month Escalation'] ,#(lf)        escalation_month#(lf)    | extend #(lf)        ['Escalation Mapping'] = case(#(lf)             ['Same month Escalation']  == 1, ""same month"",#(lf)             ['Same month Escalation']  == 0, ""after ticket created"",#(lf)             ['Same month Escalation']  == 2, ""before ticket created"",#(lf)            ""unknown""#(lf)        );#(lf)BridgeEscalationsIssue", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"issue created date", type date}, {"Ticket Created Date", type date}, {"Ticket Solved Date", type date}, {"escalation_month", type datetime}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

