table CalendarDate
	lineageTag: 1d3d5d58-8188-4e84-b2f9-9923ebe9af2e

	measure 'Total Active Tickets' = ```
			
			CALCULATE ( COUNT ( DimTicket[Ticket ID] ) )
			
			```
		formatString: #,0
		displayFolder: Deflection Category
		lineageTag: 697be0d6-959a-4913-aae6-24be480fd48b

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure 'Fiscal Quarter Flag' = ```
			
			VAR CurrentYear =
			    YEAR ( TODAY () )
			VAR FiscalYearStart =
			    DATE ( CurrentYear - IF ( MONTH ( TODAY () ) < 7, 1, 0 ), 7, 1 )
			VAR FiscalYearEnd =
			    DATE ( CurrentYear + IF ( MONTH ( TODAY () ) < 7, 0, 1 ), 6, 30 )
			VAR CurrentQuarterStart =
			    DATE ( CurrentYear, 3 * QUARTER ( TODAY () ) - 2, 1 )
			VAR CurrentQuarterEnd =
			    EOMONTH ( CurrentQuarterStart, 2 )
			RETURN
			    IF (
			        MAX ( CalendarDate[Date] ) >= FiscalYearStart
			            && MAX ( CalendarDate[Date] ) <= FiscalYearEnd
			            && MAX ( CalendarDate[Date] ) >= CurrentQuarterStart
			            && MAX ( CalendarDate[Date] ) <= CurrentQuarterEnd,
			        "Current Quarter of Current Fiscal Year",
			        "Other Fiscal Year"
			    )
			
			```
		lineageTag: 1ac3eb9d-efe0-48fe-be4b-dd9bc5d7f208

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING","PROVIDE_FORMAT_STRING_FOR_MEASURES"]}

	measure 'max FQ' = ```
			
			MAX ( CalendarDate[Fiscal Quarter] )
			
			```
		formatString: #,0
		lineageTag: 3040c92d-9533-4ef5-9099-ffdfd5fbb72a

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","FIRST_LETTER_OF_OBJECTS_MUST_BE_CAPITALIZED"]}

	measure roundup = ```
			
			QUARTER ( TODAY () ) - 2
			
			```
		formatString: #,0
		lineageTag: dfcaa306-a063-4608-814e-9c6388504aeb

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","FIRST_LETTER_OF_OBJECTS_MUST_BE_CAPITALIZED"]}

	measure 'Current Month Flag' = ```
			
			
			VAR CurrentYear =
			    YEAR ( TODAY () )
			VAR CurrentMonth =
			    MONTH ( TODAY () )
			
			  
			RETURN
			    IF (
			       CurrentMonth  = MONTH( MAX(CalendarDate[Date]))
			            && CurrentYear =YEAR( MAX(CalendarDate[Date])),
			        "Current Month",
			        "Other Month"
			    )
			
			```
		lineageTag: f2dadc5a-22be-4aeb-858f-2bb1da7aca36

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING","PROVIDE_FORMAT_STRING_FOR_MEASURES"]}

	measure 'Current Month' = ```
			
			
			 TODAY()
			
			```
		formatString: mmmm yyyy
		lineageTag: a864c7af-ecae-4a8f-93a9-d4476da71507

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure dummy = ```
			
			VAR MaxSelectedDate =
			    MAX('CalendarDate'[Date])  -- Find the maximum selected date
			VAR StartDate =
			    EOMONTH(MaxSelectedDate, -6) + 1  -- Start of the 6-month range
			VAR EndDate =
			    EOMONTH(MaxSelectedDate, 0)  -- End of the 6-month range
			
			RETURN
			    IF(
			        MAX('CalendarDate'[Date]) >= StartDate && MAX('CalendarDate'[Date]) <= EndDate,
			        TRUE(),
			        FALSE()
			    )
			
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5b01862e-9d4d-4582-bbf5-b3a0b49e7107

	column fiscal_half_name
		dataType: string
		lineageTag: 34c75a4c-abce-4b2f-a75a-39b57256ea43
		summarizeBy: none
		sourceColumn: fiscal_half_name

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Is Closed Month' = ```
			
			IF (
			    AND (
			        MONTH ( CalendarDate[Month] ) = MONTH ( EOMONTH ( TODAY (), -1 ) ),
			        YEAR ( 'CalendarDate'[Date]) = YEAR ( EOMONTH ( TODAY (), -1 ) )
			    ),
			    TRUE ,
			    FALSE ()
			)
			
			```
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Forecasting Ticket Trends Measures
		lineageTag: 1b1495df-ce88-4ca9-9d0f-43ae1a2a91e9
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Is Second Closed Month' = ```
			
			IF (
			    AND (
			        MONTH ( CalendarDate[Month] ) = MONTH ( EOMONTH ( TODAY (), -2 ) ),
			        YEAR ( 'CalendarDate'[Date]) = YEAR ( EOMONTH ( TODAY (), -2 ) )
			    ),
			    TRUE ,
			    FALSE ()
			)
			
			```
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Forecasting Ticket Trends Measures
		lineageTag: 6d35ce82-2146-4267-86bc-1d5f9d4b61eb
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Is Third Closed Month' = ```
			
			IF (
			    AND (
			        MONTH ( CalendarDate[Month] ) = MONTH ( EOMONTH ( TODAY (), -3 ) ),
			        YEAR ( 'CalendarDate'[Date]) = YEAR ( EOMONTH ( TODAY (), -3) )
			    ),
			    TRUE (),
			    FALSE ()
			)
			
			```
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Forecasting Ticket Trends Measures
		lineageTag: 21c2790c-1fc6-41df-9e44-4444ce9175dd
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Is Fourth Closed Month' = ```
			
			IF (
			    AND (
			        MONTH ( CalendarDate[Month] ) = MONTH ( EOMONTH ( TODAY (), -4 ) ),
			        YEAR ( 'CalendarDate'[Date]) = YEAR ( EOMONTH ( TODAY (), -4) )
			    ),
			    TRUE (),
			    FALSE ()
			)
			
			```
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Forecasting Ticket Trends Measures
		lineageTag: e3b1f807-84b3-4442-9208-57e2a70fbd8c
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Is Fifth Closed Month' = ```
			
			IF (
			    AND (
			        MONTH ( CalendarDate[Month] ) = MONTH ( EOMONTH ( TODAY (), -5 ) ),
			        YEAR ( 'CalendarDate'[Date]) = YEAR ( EOMONTH ( TODAY (), -5) )
			    ),
			    TRUE (),
			    FALSE ()
			)
			
			```
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Forecasting Ticket Trends Measures
		lineageTag: 3c06347a-1425-4cd1-b443-0dae16c7af32
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column Week = ```
			
			CONCATENATE (
			    CONCATENATE (
			        CONCATENATE (
			            CONCATENATE (
			                CONCATENATE (
			                    CONCATENATE ( MONTH ( 'CalendarDate'[Week Starting Date] ), "/" ),
			                    DAY ( 'CalendarDate'[Week Starting Date] )
			                ),
			                " - "
			            ),
			            MONTH ( 'CalendarDate'[Week Ending Date])
			        ),
			        "/"
			    ),
			    DAY ( 'CalendarDate'[Week Ending Date] )
			)
			
			```
		lineageTag: d1e074e9-2e72-4273-a359-d96016b377dd
		summarizeBy: none
		sortByColumn: 'Week Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Month Name Desc' = -CalendarDate[Month]
		formatString: #,0.00
		lineageTag: 51544a90-2965-4d4e-af14-17834500e091
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Month Desc' = CalendarDate[Month]
		lineageTag: d6ffbcd1-81fe-47b2-8707-dd66bda36f96
		summarizeBy: none
		sortByColumn: 'Month Name Desc'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_first_of_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 668f6b17-1fd1-4236-aebc-25dafc2487b2
		summarizeBy: none
		sourceColumn: is_first_of_month

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_end_of_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b73d95c6-234d-4369-a583-aa3d40c6e43d
		summarizeBy: none
		sourceColumn: is_end_of_month

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_first_of_fiscal_quarter
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4e638452-e65d-4dd5-8de1-f4eb35491bfb
		summarizeBy: none
		sourceColumn: is_first_of_fiscal_quarter

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_end_of_fiscal_quarter
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f65b327-49a7-497f-a1a0-155f1e7f61c9
		summarizeBy: none
		sourceColumn: is_end_of_fiscal_quarter

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_latest_snapshot_day
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c5c3698f-6a54-4e56-8deb-8d297b47630e
		summarizeBy: none
		sourceColumn: is_latest_snapshot_day

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_current_day
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4edcb309-9c23-4588-af37-bb64ad3b8bcd
		summarizeBy: none
		sourceColumn: is_current_day

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column is_current_day_or_eom
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0873265-22d3-4634-9e5a-2d8d65376894
		summarizeBy: none
		sourceColumn: is_current_day_or_eom

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column WeekNum = WEEKNUM('CalendarDate'[Date])
		formatString: #,0
		lineageTag: f1d7123f-755a-4e79-a77b-92ab3760b816
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column YearMonthWeek = ```
			
			VAR week_start = CONCATENATE(
			    MONTH('CalendarDate'[Week Starting Date]),  
			    DAY('CalendarDate'[Week Starting Date])
			)
			VAR week_end = CONCATENATE(
			    MONTH('CalendarDate'[Week Ending Date]),  
			    DAY('CalendarDate'[Week Ending Date])
			)
			VAR week_s_end = CONCATENATE(week_start, week_end)
			RETURN 
			 CONCATENATE(
			    'CalendarDate'[Year],
			    week_s_end
			)
			```
		lineageTag: b56680a5-675f-412b-bf33-6cae4c22e9fe
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","MONTH_(AS_A_STRING)_MUST_BE_SORTED"]}

	column 'Week Order' = ```
			
			Var Week =
			CONCATENATE (
			    CONCATENATE (
			        CONCATENATE (
			            CONCATENATE (
			                CONCATENATE (
			                    CONCATENATE (
			                        CONCATENATE (
			                            CONCATENATE ( MONTH ( CalendarDate[Week Starting Date] ), "/" ),
			                            DAY ( CalendarDate[Week Starting Date] )
			                        ),
			                        CONCATENATE ( "/", YEAR ( CalendarDate[Week Starting Date] ) )
			                    ),
			                    " - "
			                ),
			                MONTH ( CalendarDate[Week Ending Date] )
			            ),
			            "/"
			        ),
			        DAY ( CalendarDate[Week Ending Date] )
			    ),
			    CONCATENATE ( "/", YEAR ( CalendarDate[Week Ending Date] ) )
			)
			
			RETURN
			    DATEVALUE ( LEFT ( Week, FIND ( "-", Week ) - 1 ) )
			
			```
		formatString: General Date
		lineageTag: cd185e43-b4ed-488b-9c9b-ffc93ca92394
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Month Default'
		dataType: string
		lineageTag: a7a9b038-463e-464f-b98c-a1a9ad22f73d
		summarizeBy: none
		sourceColumn: Month Default
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","MONTH_(AS_A_STRING)_MUST_BE_SORTED"]}

	column is_current_day_or_fom
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c7b9adca-4ad8-42d0-b983-b7fbfd66a5f7
		summarizeBy: none
		sourceColumn: is_current_day_or_fom

		annotation SummarizationSetBy = Automatic

	column 'Quarter Ticket Volume' = ```
			IF (
			    CONTAINSSTRING ( CalendarDate[Month], "Jan" )
			        || CONTAINSSTRING ( CalendarDate[Month], "Apr" )
			        || CONTAINSSTRING ( CalendarDate[Month], "Jul" )
			        || CONTAINSSTRING ( CalendarDate[Month], "Oct" ),
			    "Month 1",
			    IF (
			        CONTAINSSTRING ( CalendarDate[Month], "Feb" )
			            || CONTAINSSTRING ( CalendarDate[Month], "May" )
			            || CONTAINSSTRING ( CalendarDate[Month], "Aug" )
			            || CONTAINSSTRING ( CalendarDate[Month], "Nov" ),
			        "Month 2",
			        IF (
			            CONTAINSSTRING ( CalendarDate[Month], "Mar" )
			                || CONTAINSSTRING ( CalendarDate[Month], "Jun" )
			                || CONTAINSSTRING ( CalendarDate[Month], "Sep" )
			                || CONTAINSSTRING ( CalendarDate[Month], "Dec" ),
			            "Month 3"
			        )
			    )
			)
			
			```
		lineageTag: 3e55bd62-36d3-466a-be58-47c5bb3e695b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsRollingSixMonth =
			
			
			var yearmonth =CALCULATE(
			    MAX(CalendarDate[Year Month]), CalendarDate[Date]=TODAY()
			)
			RETURN
			IF (CalendarDate[Year Month] >= yearmonth -5,TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8703d7d7-0517-41c6-baad-7c9758a20f37
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Ending Date' =
			
			var MonthEndDate = EOMONTH(CalendarDate[Date], 0)
			return IF(MonthEndDate<=TODAY(), MonthEndDate, TODAY())
		formatString: m/d/yyyy
		lineageTag: f769e80b-ec94-4f6c-8189-66368b84c48b
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Quarter Ending Date' = ```
			
			VAR QuarterEndDate = 
			    SWITCH(
			        TRUE(),
			        CalendarDate[Quarter] = 1, DATE(YEAR(CalendarDate[Date]), 3, 31),
			        CalendarDate[Quarter] = 2, DATE(YEAR(CalendarDate[Date]), 6, 30),
			        CalendarDate[Quarter] = 3, DATE(YEAR(CalendarDate[Date]), 9, 30),
			        CalendarDate[Quarter] = 4, DATE(YEAR(CalendarDate[Date]), 12, 31)
			    )
			RETURN IF ( QuarterEndDate <= TODAY(), QuarterEndDate, TODAY() )
			
			```
		formatString: m/d/yyyy
		lineageTag: 70d6d241-94e8-4064-8f64-48cef82a778f
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Fiscal Month of Year' = IF(CalendarDate[Month of Year] >= 7, CalendarDate[Month of Year] - 6, CalendarDate[Month of Year] + 6 )
		formatString: 0
		lineageTag: aac78748-d242-4bd7-af87-653996cc1522
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Short term Forecast Flag' =
			
			VAR PeriodStart = EOMONTH(TODAY(), -3)
			VAR PeriodEnd = EOMONTH(TODAY(), 2)
			RETURN IF(CalendarDate[Date]>= DATE(YEAR(PeriodStart), MONTH(PeriodStart), 1) && CalendarDate[Date] <= PeriodEnd, TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 77b7a61d-295a-496f-9a2b-e75c8467934b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Short' = "Q" & CalendarDate[Fiscal Quarter]
		lineageTag: a2031993-20c7-416a-b5c4-8a944d5e71cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Previous_Month_Column = ```
			
			VAR CurrentMonthYear = FORMAT(TODAY(), "MMM YYYY")
			VAR SelectedMonthYear = FORMAT('CalendarDate'[Month Default], "MMM YYYY")
			VAR PreviousMonthYear = FORMAT(EDATE(TODAY(), -1), "MMM YYYY")
			
			RETURN 
			IF(SelectedMonthYear = PreviousMonthYear, "Previous Month", SelectedMonthYear)
			
			```
		lineageTag: b9639d65-5743-4b92-8644-6924a35a06ae
		summarizeBy: none
		sortByColumn: 'Previous_Month_Column Key'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Short term Forecast Flag 2' = ```
			
			VAR SelectedMonth = MAX(CalendarDate[Month])  -- Ensure a single value is selected
			VAR PeriodStart = DATE(YEAR(SelectedMonth), MONTH(SelectedMonth) - 5, 1)  -- First day of the month 5 months ago
			VAR PeriodEnd = EOMONTH(SelectedMonth, 0)  -- End of the selected month
			
			RETURN 
			    IF(
			        CalendarDate[Date] >= PeriodStart && 
			        CalendarDate[Date] <= PeriodEnd, 
			        TRUE(), 
			        FALSE()
			    )
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7cc976c3-6031-4212-8bab-7e6380785a83
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Previous_Month_Column Key' = ```
			
			// VAR CurrentMonthYear = FORMAT(TODAY(), "MMM YYYY")
			// VAR SelectedMonthYear = FORMAT('CalendarDate'[Month Default], "MMM YYYY")
			// VAR PreviousMonthYear = FORMAT(EDATE(TODAY(), -1), "MMM YYYY")
			
			// RETURN 
			// IF(SelectedMonthYear = PreviousMonthYear, "Previous Month", SelectedMonthYear)
			YEAR(CalendarDate[Date])*100 + MONTH(CalendarDate[Date])
			```
		formatString: 0
		lineageTag: b4b46f1d-f111-4f31-9558-cf623d514cd9
		summarizeBy: count

		annotation SummarizationSetBy = Automatic

	column is_current_fiscal_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 313f43f8-3916-45bb-b80d-108bdc8f864a
		summarizeBy: none
		sourceColumn: is_current_fiscal_year

		annotation SummarizationSetBy = Automatic

	column is_previous_fiscal_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8fd09de5-587e-4153-9e83-a263e8eb36d8
		summarizeBy: none
		sourceColumn: is_previous_fiscal_year

		annotation SummarizationSetBy = Automatic

	column number_of_fiscal_years_ago
		dataType: int64
		formatString: 0
		lineageTag: fa61d568-2af4-4bb9-9828-6a447e2cc412
		summarizeBy: sum
		sourceColumn: number_of_fiscal_years_ago

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: string
		lineageTag: 2aa81871-4054-4eee-87ab-ca9bf55b06b9
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d7d29376-ec57-4f33-a7f0-f598d8fd2853
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Month of Year'
		dataType: int64
		formatString: 0
		lineageTag: 9d30d58a-f6c4-4e3d-bc4d-43cce6e41b31
		summarizeBy: sum
		sourceColumn: Month of Year

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: M/d/yyyy
		lineageTag: 63d804db-c8d4-4e6d-90bb-50a3ced2a8e4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Day of Month'
		dataType: int64
		formatString: 0
		lineageTag: 87e240d7-7e7f-4b0c-aa5e-fb4f855d2526
		summarizeBy: sum
		sourceColumn: Day of Month

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: b7eb3301-ba61-4d10-8cd2-36ac275f76b2
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 94515bff-d115-411d-bb97-63875f3f40fc
		summarizeBy: sum
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column 'Day Short Name'
		dataType: string
		lineageTag: c70bd49e-453d-44e9-9005-8f1bad1be322
		summarizeBy: none
		sourceColumn: Day Short Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 19387f1f-82a6-46f2-a10d-bf826b1be789
		summarizeBy: sum
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Name'
		dataType: string
		lineageTag: 6936c451-8000-4f27-a26c-0ccfec9cc793
		summarizeBy: none
		sourceColumn: Fiscal Quarter Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 4041346e-a716-4479-b2ce-5bff4d3cb844
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Name'
		dataType: string
		lineageTag: 3d4dbd92-21e2-4db2-a468-f1b1aa8c6ccc
		summarizeBy: none
		sourceColumn: Fiscal Year Name

		annotation SummarizationSetBy = Automatic

	column 'Is Business Day?'
		dataType: int64
		formatString: 0
		lineageTag: de99d617-ec54-4671-b4f2-8e3bc871e493
		summarizeBy: sum
		sourceColumn: Is Business Day?

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 00396be8-250e-4318-afcf-ad0cbbd8c5b5
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Year Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 76768fb3-5804-4707-8ef4-217527601615
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Fiscal Month of Year'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Short Name'
		dataType: string
		lineageTag: 3e4d0662-bf4f-478f-bb6f-fef431db90d9
		summarizeBy: none
		sourceColumn: Month Short Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 66276e01-a5bc-4840-916e-9d9e66013af2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column 'Week Ending Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5bb0bfd1-9b5e-4b08-a63b-5af2752ba050
		summarizeBy: none
		sourceColumn: Week Ending Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week Starting Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c558e0f-7b40-4373-8fdf-299e090a56b7
		summarizeBy: none
		sourceColumn: Week Starting Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Month'
		dataType: int64
		formatString: 0
		lineageTag: 82da0c42-24ca-4491-9573-df146d789c07
		summarizeBy: sum
		sourceColumn: Year Month

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Is Current Day'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3e83d934-662b-4f59-adba-2e8a60abc2a6
		summarizeBy: none
		sourceColumn: Is Current Day

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Fiscal Year Hierarchy'
		lineageTag: 6cc60942-d4d0-48d1-b5bc-ac729b6c7b95

		level 'Fiscal Year Name'
			lineageTag: a0380adb-ca4e-4753-a5b3-c072ebd5c6d2
			column: 'Fiscal Year Name'

		level 'Fiscal Quarter Name'
			lineageTag: 7bb9d26c-4aef-4547-af9b-a0773b7eee47
			column: 'Fiscal Quarter Name'

		level Month
			lineageTag: 53815455-e52a-4933-b3ea-b2105e37326f
			column: Month

		level Week
			lineageTag: 82bb4b25-499b-44c4-b325-e8e0a2fb6c5f
			column: Week

		level Date
			lineageTag: 6f3a4a32-6c0e-4938-9903-23e53638c772
			column: Date

	hierarchy 'Date Hierarchy Calendar'
		lineageTag: a874f007-7ed8-46ac-84d0-4f16ce685067

		level Year
			lineageTag: d8e3824e-eb65-48ef-b245-0bdc1698fe75
			column: Year

		level Quarter
			lineageTag: fd0f10ad-f0df-41e7-8d05-10a1e7e6f5e8
			column: Quarter

		level Month
			lineageTag: 7d65d2e4-8dfb-4a2b-8ebb-9a231eca60c5
			column: Month

		level Week
			lineageTag: 8f2dab33-ab3b-45ab-893a-104dd5cb1d1a
			column: Week

		level Date
			lineageTag: d9774de1-2002-49ce-8ee3-0e8e33716e77
			column: Date

	partition CalendarDate-f60060c5-21c7-4cb0-ab7d-4df5f0fe0818 = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "calendar_date#(lf)| project #(lf)    Day = day_long_name,#(lf)    Year = year,#(lf)    ['Month of Year'] = month_of_year,#(lf)    Date = ['date'],#(lf)    [""Day of Month""] = day_of_month,#(lf)    [""Day of Week""] = day_of_week,#(lf)    [""Day of Year""] = day_of_year,#(lf)    [""Day Short Name""] = day_short_name,#(lf)    [""Fiscal Quarter""] = fiscal_quarter,#(lf)    [""Fiscal Quarter Name""] = fiscal_quarter_name,#(lf)    [""Fiscal Year""] = fiscal_year,#(lf)    [""Fiscal Year Name""] = fiscal_year_name,#(lf)    [""Is Business Day?""] = is_business_day,#(lf)    Month = month,#(lf)    [""Month Name""] = month_name,#(lf)    ['Month Short Name'] = month_short_name,#(lf)    Quarter = quarter,#(lf)    ['Week Ending Date'] = week_ending_date,#(lf)    ['Week Starting Date'] = week_starting_date,#(lf)    ['Year Month'] = year_month,#(lf)    ['Is Current Day'] = is_current_day,#(lf)    fiscal_half_name,#(lf)    is_first_of_month,#(lf)    is_end_of_month,#(lf)    is_first_of_fiscal_quarter,#(lf)    is_end_of_fiscal_quarter,#(lf)    is_latest_snapshot_day,#(lf)    is_current_day,#(lf)    is_current_day_or_eom,#(lf)    is_current_day_or_fom,#(lf)    is_current_fiscal_year,#(lf)    is_previous_fiscal_year,#(lf)    number_of_fiscal_years_ago#(lf)| extend ['Month Default'] = iif(#(lf)      ['Month of Year']  == datetime_part(""month"", now()) and Year == datetime_part(""year"", now()),#(lf)      ""Current Month"",#(lf)      strcat(['Month Short Name'], "" "", tostring(Year))#(lf)  )", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"Day", type text}, {"Week Starting Date", type date}, {"Week Ending Date", type date}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES","DATE/CALENDAR_TABLES_SHOULD_BE_MARKED_AS_A_DATE_TABLE"]}

	annotation PBI_NavigationStepName = Navigation

