table CapacityForecastforLatestForecastDate
	isHidden
	lineageTag: 28c6c783-33dd-4550-a6fe-90b5600a7e5d

	column Month
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: c549efc2-62c9-40a8-be8b-7e77e5c8d43c
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Latest Forecast Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 0d3ec1a6-c411-455c-aefd-3d84381e0629
		summarizeBy: none
		sourceColumn: Latest Forecast Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CapacityForecastforLatestForecastDate = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(Lakehouse_Endpoint, "cs_analytics"),
				    dbo_capacity_forecast_output = Source{[Schema="dbo",Item="capacity_forecast_output"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_capacity_forecast_output,{"ramped_capacity", "fte_ramped_capacity", "xr_ramped_capacity", "team", "squad", "tickets_forecast"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"month_end", "Month"}, {"total_headcount_forecast", "Headcount Forecasted"}, {"fte_headcount_forecast", "Headcount Forecasted - FTE"}, {"xr_headcount_forecast", "Headcount Forecasted  - XR"}, {"forecast_run_date", "Forecast Run Date"}}),
				    #"Grouped Rows" = Table.Group(#"Renamed Columns", {"Month"}, {{"Latest Forecast Date", each List.Max([Forecast Run Date]), type nullable date}})
				in
				    #"Grouped Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

