table DimEntitySalesforceAccount
	lineageTag: f833dc87-5218-420a-a7b9-b8410f0b209c

	column 'Totango URL' = ```
			
			
			    "https://app.totango.com/t01/github-prod/#/accounts/" &  
			    DimEntitySalesforceAccount[Salesforce Account ID]
			```
		lineageTag: a8f5d657-400a-4a51-ae72-0fea7026516a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Salesforce Account ID'
		dataType: string
		lineageTag: 375cbb0b-7d9d-4166-9af2-729148f5e462
		summarizeBy: none
		sourceColumn: Salesforce Account ID

		annotation SummarizationSetBy = Automatic

	column 'Salesforce Name'
		dataType: string
		lineageTag: 2b5b2486-e302-4a5b-998c-2267d68f4569
		summarizeBy: none
		sourceColumn: Salesforce Name

		annotation SummarizationSetBy = Automatic

	column 'Mapped Support Plan Current'
		dataType: string
		lineageTag: 9e69d36c-e9e2-4cac-afa2-b50c26aaadbc
		summarizeBy: none
		sourceColumn: Mapped Support Plan Current

		annotation SummarizationSetBy = Automatic

	column 'Final Support Plan Current'
		dataType: string
		lineageTag: 6db6076d-acf5-4a4b-a90d-3ee2787aae37
		summarizeBy: none
		sourceColumn: Final Support Plan Current

		annotation SummarizationSetBy = Automatic

	column 'Final Support  Plan Source Current'
		dataType: string
		lineageTag: 455a69df-56cb-4978-bb8b-7061a45e7e37
		summarizeBy: none
		sourceColumn: Final Support  Plan Source Current

		annotation SummarizationSetBy = Automatic

	column 'Is  License MS Paper Current'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6b7ff3b4-03f3-447d-9eb4-b406f4e39de6
		summarizeBy: none
		sourceColumn: Is  License MS Paper Current

		annotation SummarizationSetBy = Automatic

	column 'Is Support MS Paper Current'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c21114e5-3d24-48aa-a006-6ddc1baa7813
		summarizeBy: none
		sourceColumn: Is Support MS Paper Current

		annotation SummarizationSetBy = Automatic

	column 'License ARR Current'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 41321f3c-0851-4548-a26d-a6f3487f0e8c
		summarizeBy: sum
		sourceColumn: License ARR Current

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Proxy For Total Support Arr GH Plus MSFT  Current'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: eee43f5c-5cd9-4ebf-bfa8-7e85d196335e
		summarizeBy: sum
		sourceColumn: Proxy For Total Support Arr GH Plus MSFT  Current

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Azure Category Spend Current'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 117a2ecb-1bd6-443b-bb25-b430832ae21a
		summarizeBy: sum
		sourceColumn: Azure Category Spend Current

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'GitHub Support ARR Embedded In Unified Current'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: c7fa3ee1-dfaf-4304-8a74-ba12d0f899b9
		summarizeBy: sum
		sourceColumn: GitHub Support ARR Embedded In Unified Current

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	partition DimEntitySalesforceAccount = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_entity_salesforce_account_dim #(lf)| where is_in_support_team == ""TRUE"" #(lf)     and is_in_support_squad == ""TRUE"" #(lf)     and has_ticket_within_two_years == ""TRUE"" #(lf)     and salesforce_account_id != "" "" #(lf)| project #(lf)     [""Salesforce Account ID""] = salesforce_account_id, #(lf)     [""Salesforce Name""] =  iif(entity_name == """", ""(Blank)"", entity_name), #(lf)     [""Mapped Support Plan Current""] = mapped_support_plan_current, #(lf)     [""Final Support Plan Current""] = final_support_plan_current, #(lf)     [""Final Support  Plan Source Current""] = final_support_plan_source_current, #(lf)     [""Is  License MS Paper Current""] = is_license_ms_paper_current, #(lf)     [""Is Support MS Paper Current""] = is_support_ms_paper_current, #(lf)     [""License ARR Current""] = license_arr_current, #(lf)     [""Proxy For Total Support Arr GH Plus MSFT  Current""] = proxy_for_total_support_arr_gh_plus_msft_current, #(lf)     [""Azure Category Spend Current""] = azure_category_spend_current, #(lf)     [""GitHub Support ARR Embedded In Unified Current""] = github_support_arr_embedded_in_unified_current ", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"License ARR Current", Currency.Type}, {"Proxy For Total Support Arr GH Plus MSFT  Current", Currency.Type}, {"Azure Category Spend Current", Currency.Type}, {"GitHub Support ARR Embedded In Unified Current", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

