table DimFCPProduct
	lineageTag: f67d171c-1535-47e0-b7f1-33e371c72b31

	column 'Product ID'
		dataType: string
		lineageTag: 961765a7-f5b1-4263-9560-99456da11722
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 1b99a75e-68eb-48d7-ad44-8bdda7ff8f90
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh At'
		dataType: dateTime
		formatString: General Date
		lineageTag: afec8603-36c6-49b5-873a-457f82e1b77b
		summarizeBy: none
		sourceColumn: Last Refresh At

		annotation SummarizationSetBy = Automatic

	partition DimFCPProduct = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_fcp_product_dim #(lf)| extend ProductID = iif(isnull(product_id), ""0"", tostring(product_id)) #(lf)| project  #(lf)     [""Product ID""] = ProductID, #(lf)     [""Product Name""] = product, #(lf)     [""Last Refresh At""] = dag_last_run_at ", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Last Refresh At", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

