table DimLeadingLaggingURL
	lineageTag: f976b858-788a-4bc3-b258-df7645a99d23

	column Team
		dataType: string
		lineageTag: e993275a-2786-4c71-bdf1-c9d23ca91874
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Team_1
		dataType: string
		lineageTag: 585089cc-4c79-49ae-9ce9-2ae370f1f11c
		summarizeBy: none
		sourceColumn: Team_1

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Core Metric'
		dataType: string
		lineageTag: 78f6d7a8-ca0e-40ec-87f4-5b59f0240c83
		summarizeBy: none
		sourceColumn: Core Metric
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column URL
		dataType: string
		lineageTag: b5e2fc64-98ed-439f-a753-27b8bda0962a
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 731988df-0bc2-4273-8767-e90d1beeaa11
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	partition DimLeadingLaggingURL = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Leading%20and%20Lagging%20Indicators%20URLs.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Index", Int64.Type}, {"Team", type text}, {"Team_1", type text}, {"Core Metric", type text}, {"URL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS","OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

