table DimSupportPlanDetails
	lineageTag: 6fce6f4c-065e-4b35-ad0a-9f77d1899c1b

	column entity_id
		dataType: string
		lineageTag: c438fbab-c92d-429b-98f0-2a105347a261
		summarizeBy: none
		sourceColumn: entity_id

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column entity_type
		dataType: string
		lineageTag: f941a5d1-6d76-411b-ba3a-211ad3b3fbfc
		summarizeBy: none
		sourceColumn: entity_type

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column entity_name
		dataType: string
		lineageTag: f80f15cd-52ec-4391-a3dc-557886584699
		summarizeBy: none
		sourceColumn: entity_name

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column associated_salesforce_account_id_with_support
		dataType: string
		lineageTag: 6748e2cc-31c4-4274-aae6-a0070911cbbc
		summarizeBy: none
		sourceColumn: associated_salesforce_account_id_with_support

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column mapped_support_plan
		dataType: string
		lineageTag: f33ff5e3-9b96-4009-a3dd-bcde01427284
		summarizeBy: none
		sourceColumn: mapped_support_plan

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column final_support_plan
		dataType: string
		lineageTag: f510addc-8013-4139-a36d-19139ef4c5ad
		summarizeBy: none
		sourceColumn: final_support_plan

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column final_support_plan_source
		dataType: string
		lineageTag: f135ef3c-39ac-40fd-9752-863f3694f76d
		summarizeBy: none
		sourceColumn: final_support_plan_source

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column harmony_entitlement
		dataType: string
		lineageTag: 19108cf5-7ad0-4780-adaf-7966907dc780
		summarizeBy: none
		sourceColumn: harmony_entitlement

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column salesforce_support_plan
		dataType: string
		lineageTag: a48abdfe-6d24-43dc-a439-c3b38d63ddd1
		summarizeBy: none
		sourceColumn: salesforce_support_plan

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column ean
		dataType: string
		lineageTag: 603ed96b-fa70-4230-9e62-7f117788e13c
		summarizeBy: none
		sourceColumn: ean

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column pcn
		dataType: string
		lineageTag: 2672df01-0468-46df-974b-a5e2712ef4ae
		summarizeBy: none
		sourceColumn: pcn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column license_arr
		dataType: double
		lineageTag: b6792354-cb30-412a-a344-a2f4b820c770
		summarizeBy: sum
		sourceColumn: license_arr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column license_seats
		dataType: double
		lineageTag: 926b635b-b3dd-4ea1-8951-d38be8e172b7
		summarizeBy: sum
		sourceColumn: license_seats

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column azure_category_spend
		dataType: double
		lineageTag: 3d0665c4-c17c-4364-a457-3db98b937926
		summarizeBy: sum
		sourceColumn: azure_category_spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column github_support_arr_embedded_in_unified
		dataType: double
		lineageTag: e40de4ca-b765-483e-9a2f-c925cf53d12f
		summarizeBy: sum
		sourceColumn: github_support_arr_embedded_in_unified

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 41f46844-185a-4707-a525-5b26dc13980a
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b6ea39e-f2d0-4ebc-954e-0ad41e00958b
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column day
		dataType: dateTime
		formatString: General Date
		lineageTag: 78101643-a94a-4363-a639-b8edef6805be
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column entity_type_id
		dataType: string
		lineageTag: 13a83b1a-736d-4ea1-8f2b-968c91dadf87
		summarizeBy: none
		sourceColumn: entity_type_id

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Support ARR'
		dataType: double
		lineageTag: 19e188f0-19f0-45f2-958f-8577df0e8a47
		summarizeBy: sum
		sourceColumn: Support ARR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Proxy for Total Support ARR GH plus MSFT'
		dataType: double
		lineageTag: 1f8b361d-54e4-4bbc-abd7-58a0747245e8
		summarizeBy: sum
		sourceColumn: Proxy for Total Support ARR GH plus MSFT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimSupportPlanDetails = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""c360"").dim_support_plan_details #(lf)| where entity_type == ""Salesforce Account"" #(lf)| distinct * #(lf)| project-rename  #(lf)     [""Proxy for Total Support ARR GH plus MSFT""] = proxy_for_total_support_arr_gh_plus_msft, #(lf)     [""Support ARR""] = support_arr #(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				        #"Changed Type" = Table.TransformColumnTypes(Source,{{"entity_id", type text}, {"start_date", type datetime}, {"end_date", type datetime}, {"day", type datetime}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

