table DimServerInstallations
	lineageTag: 5b515757-6aa9-4bbd-88d8-6e3afb3e885b

	measure 'Count Installations' = ```
			
			COUNT ( FactServerInstallations[installation_id] )
			
			```
		formatString: 0
		lineageTag: 9cfaeeb8-3f0f-4be8-bfad-c1cbcabee46e

	column 'Customer Name'
		dataType: string
		lineageTag: 6c8c905b-d160-47d4-aae4-01994de384cd
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Features
		dataType: string
		lineageTag: f9bfa460-5bea-464f-a8e8-3ca53e6da569
		summarizeBy: none
		sourceColumn: Features

		annotation SummarizationSetBy = Automatic

	column 'Installation ID'
		dataType: double
		lineageTag: 186f6a08-15e5-4bd7-aaaa-19166113387b
		summarizeBy: none
		sourceColumn: Installation ID

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Owner Type'
		dataType: string
		lineageTag: b1b131ee-8c84-4e20-a09f-92bc9ccad09f
		summarizeBy: none
		sourceColumn: Owner Type

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 600013e0-67e1-4e58-bbea-062adafd7712
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	partition DimServerInstallations-26e37cb9-726a-4452-b649-6967c98bd333 = m
		mode: import
		source =
				// DimServerInstallations1
				let
				    Source = AzureDataExplorer.Contents(
				        "gh-analytics.eastus.kusto.windows.net",
				        "service_cs_analytics",
				        "database(""service_cs_analytics"").supportv3_server_installations_dim#(lf)| project#(lf)    [""Customer Name""] = customer_name,#(lf)    [""Features""] = features,#(lf)    [""Installation ID""] = installation_id,#(lf)    [""Owner Type""] = owner_type,#(lf)    [""Version""] = version",
				        [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"Installation ID", type number},
				        {"Features", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

