table DimScorecard
	lineageTag: 3b730516-4709-478e-8d65-7ed55b89c34f

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 48242c88-feff-4619-bdc0-862a21bae26b
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Team
		dataType: string
		lineageTag: bcd9a408-2fd6-46e1-8da1-3b10c43b109d
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Metric
		dataType: string
		lineageTag: 1f4b8d50-cfec-4575-aec7-3afc2374c120
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Target
		dataType: double
		lineageTag: 10bd6bbc-d24d-4646-b6a1-94e446989268
		summarizeBy: none
		sourceColumn: Target

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column URL
		dataType: string
		lineageTag: fc78b92c-4499-416f-b527-38baeda390b2
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	partition DimScorecard = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Team%20Scorecard%20Metrics.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Sheet1_Sheet, each ([Column1] <> null)),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Index", Int64.Type}, {"Team", type text}, {"Metric", type text}, {"Target", type number}, {"URL", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS","OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

