table DimSHIMeasures
	excludeFromModelRefresh
	lineageTag: 4e80e61e-798b-4ef7-8a5c-5b6bed28b638

	column 'Metric '
		dataType: string
		lineageTag: be33854c-93bd-446c-81dc-3c3d63f9a5c5
		summarizeBy: none
		sourceColumn: "Metric "

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","TRIM_OBJECT_NAMES","OBJECTS_SHOULD_NOT_START_OR_END_WITH_A_SPACE","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","MARK_PRIMARY_KEYS","HIDE_FOREIGN_KEYS"]}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 065cdd27-5135-44b3-9c3a-4d9214302057
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","MARK_PRIMARY_KEYS"]}

	column 'Metric V2' = DimSHIMeasures[Metric ]
		lineageTag: 62ddb90d-7d6a-4778-930f-58223048c8b4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	partition DimSHIMeasures-671df28f-2c80-439d-ab4f-884cd51b9138 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Support%20Health%20Index%20W_%20time%20to%20Resolved%20normalized.xlsx"), null, true),
				    #"SHI Team Metrics DEV_Sheet" = Source{[Item="SHI Team Metrics DEV",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"SHI Team Metrics DEV_Sheet", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.SelectColumns(#"Promoted Headers",{"Metric "}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 0, 1, Int64.Type),
				    #"Filtered Rows" = Table.SelectRows(#"Added Index", each ([#"Metric "] <> null and [#"Metric "] <> "" and [#"Metric "] <> "Escalation IR % Sev2 "))
				in
				    #"Filtered Rows"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES","SNOWFLAKE_SCHEMA_ARCHITECTURE"]}

