table DimTicket
	lineageTag: 1d60b64d-5777-498a-8479-881318addfa9

	measure 'Reopens Average' = ```
			
			DIVIDE (
			    CALCULATE (
			        SUM ( DimTicket[Reopens Count] ),
			        ALL ( DimAssignee[Assignee Name] ),
			        ALL ( DimManager[Manager Name] )
			    ),
			    [Total Assignees]
			)
			
			```
		formatString: #,0.00
		lineageTag: 28a3fb77-238b-40b8-a754-d21bd134e92f

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING"]}

	measure 'Reopens Sum' = ```
			
			SUM ( DimTicket[Reopens Count] )
			
			```
		formatString: #,0
		lineageTag: 7993f777-c886-492a-b248-72ff25cc44d8

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Zendesk URL' = ```
			
			CONCATENATE (
			    "https://github.zendesk.com/agent/tickets/",
			    DimTicket[Ticket ID]
			)
			
			```
		lineageTag: ad569acd-b795-4ec5-8882-453896b5a923
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Complexity Level  Number'
		dataType: int64
		lineageTag: 5890d391-2090-45e7-b08e-bd4de506a703
		summarizeBy: average
		sourceColumn: Complexity Level  Number

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	column 'Ticket ID'
		dataType: int64
		formatString: 0
		lineageTag: 812cca31-50a7-45cc-9922-53b5e6405226
		summarizeBy: none
		sourceColumn: Ticket ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: d41c0395-5e7d-4e66-a47d-ef4d68a73674
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Current Priority'
		dataType: string
		lineageTag: 8fbd3859-cebd-495f-bd89-7eaea617d3ea
		summarizeBy: none
		sourceColumn: Current Priority

		annotation SummarizationSetBy = Automatic

	column 'First Priority'
		dataType: string
		lineageTag: 24cc285b-b938-41d9-ba75-2adc0e0d5032
		summarizeBy: none
		sourceColumn: First Priority

		annotation SummarizationSetBy = Automatic

	column 'Max Priority Set by Agent'
		dataType: string
		lineageTag: c5260af3-2870-49db-8bac-f44111dc86bb
		summarizeBy: none
		sourceColumn: Max Priority Set by Agent

		annotation SummarizationSetBy = Automatic

	column 'Max Priority Set by User'
		dataType: string
		lineageTag: b7f5d4ec-5052-4564-9b30-34f281e1f550
		summarizeBy: none
		sourceColumn: Max Priority Set by User

		annotation SummarizationSetBy = Automatic

	column 'Priority At Creation'
		dataType: string
		lineageTag: cdeb3463-2f04-4920-9941-9fe96abdbea0
		summarizeBy: none
		sourceColumn: Priority At Creation

		annotation SummarizationSetBy = Automatic

	column 'Priority At Assigned'
		dataType: string
		lineageTag: 21b6b265-ae6f-4ce8-8729-9640f01c3927
		summarizeBy: none
		sourceColumn: Priority At Assigned

		annotation SummarizationSetBy = Automatic

	column 'Priority at Solved'
		dataType: string
		lineageTag: f5bc1e56-5fd2-48f6-b2c6-6307766715f1
		summarizeBy: none
		sourceColumn: Priority at Solved

		annotation SummarizationSetBy = Automatic

	column 'Spammy Reason'
		dataType: string
		lineageTag: 478050d0-2bd5-49cd-a579-044bf9eb88c8
		summarizeBy: none
		sourceColumn: Spammy Reason

		annotation SummarizationSetBy = Automatic

	column 'Is  Initial Response Eligible'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fcc77080-1d68-4e4a-a08a-74d26ccf8ce9
		summarizeBy: none
		sourceColumn: Is  Initial Response Eligible

		annotation SummarizationSetBy = Automatic

	column 'Is Initial Response Met'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d00a7611-c3fb-41a5-9797-2888e822e6d0
		summarizeBy: none
		sourceColumn: Is Initial Response Met

		annotation SummarizationSetBy = Automatic

	column 'Is Ticket Follow up'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8e313509-451b-4466-b9b0-c58cf89bbf36
		summarizeBy: none
		sourceColumn: Is Ticket Follow up

		annotation SummarizationSetBy = Automatic

	column 'Initial Response Type'
		dataType: string
		lineageTag: e083725f-6b53-45d1-a73a-f4c34c2e31eb
		summarizeBy: none
		sourceColumn: Initial Response Type

		annotation SummarizationSetBy = Automatic

	column 'Public Replies Count'
		dataType: int64
		formatString: 0
		lineageTag: fb355bfb-b6c1-4f09-83d0-bb7e06714300
		summarizeBy: sum
		sourceColumn: Public Replies Count

		annotation SummarizationSetBy = Automatic

	column 'Group Stations'
		dataType: int64
		formatString: 0
		lineageTag: 75dfefe5-8ed8-40c2-9570-5c9680abb931
		summarizeBy: sum
		sourceColumn: Group Stations

		annotation SummarizationSetBy = Automatic

	column 'Assignee Stations'
		dataType: int64
		formatString: 0
		lineageTag: f92a77dd-26f0-401e-9130-f3bb7799165a
		summarizeBy: sum
		sourceColumn: Assignee Stations

		annotation SummarizationSetBy = Automatic

	column 'Reopens Count'
		dataType: int64
		formatString: 0
		lineageTag: 4cc17a3f-7eb6-4be9-aee1-a943d4a7837f
		summarizeBy: sum
		sourceColumn: Reopens Count

		annotation SummarizationSetBy = Automatic

	column 'Is Health Check'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 18bdffeb-6fff-4540-a1ae-8075424ae4bc
		summarizeBy: none
		sourceColumn: Is Health Check

		annotation SummarizationSetBy = Automatic

	column 'Is Virtual Agent'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 602f3d61-41b9-4f29-a161-03a508985718
		summarizeBy: none
		sourceColumn: Is Virtual Agent

		annotation SummarizationSetBy = Automatic

	column 'Complexity Level'
		dataType: string
		lineageTag: 94d05a85-9a86-4bec-a2aa-15de48dcb1ad
		summarizeBy: none
		sourceColumn: Complexity Level

		annotation SummarizationSetBy = Automatic

	column 'Is Auto Triaged'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ee148caf-46fd-47e2-936e-df5759618362
		summarizeBy: none
		sourceColumn: Is Auto Triaged

		annotation SummarizationSetBy = Automatic

	column 'Preferred Language'
		dataType: string
		lineageTag: e6ede63a-3783-4a28-9ea4-d9fca2066114
		summarizeBy: none
		sourceColumn: Preferred Language

		annotation SummarizationSetBy = Automatic

	column 'Education User Type'
		dataType: string
		lineageTag: bff01f5e-b402-4431-a5db-200c0af6593c
		summarizeBy: none
		sourceColumn: Education User Type

		annotation SummarizationSetBy = Automatic

	column 'Education Subject'
		dataType: string
		lineageTag: edbc059b-3735-46a6-b270-95dab8fde9ac
		summarizeBy: none
		sourceColumn: Education Subject

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 7f984a30-c3bb-446e-acf3-3865fd73ed17
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column 'Global Region'
		dataType: string
		lineageTag: 44d4a547-3065-4ff8-8222-c7147bf03aab
		summarizeBy: none
		sourceColumn: Global Region

		annotation SummarizationSetBy = Automatic

	column 'Plan Type'
		dataType: string
		lineageTag: 6d2fca2c-18b9-424b-b85d-c61ac3d4d43d
		summarizeBy: none
		sourceColumn: Plan Type

		annotation SummarizationSetBy = Automatic

	column 'Github Org Plan'
		dataType: string
		lineageTag: 1bb2de9b-9415-4b82-9776-e8b971bab387
		summarizeBy: none
		sourceColumn: Github Org Plan

		annotation SummarizationSetBy = Automatic

	column 'Github Org Plan Rollup'
		dataType: string
		lineageTag: ed9fa58e-3204-4353-b0cb-ffbeb07d4ea9
		summarizeBy: none
		sourceColumn: Github Org Plan Rollup

		annotation SummarizationSetBy = Automatic

	column 'Github Enterprise Product Group'
		dataType: string
		lineageTag: df2b6eb6-eba1-4a53-bdd9-5b823e156d8e
		summarizeBy: none
		sourceColumn: Github Enterprise Product Group

		annotation SummarizationSetBy = Automatic

	column 'Github Business Line Rollup'
		dataType: string
		lineageTag: 3d5bdbf0-9c93-4dc7-964e-bd7f12d5ded6
		summarizeBy: none
		sourceColumn: Github Business Line Rollup

		annotation SummarizationSetBy = Automatic

	column 'Github Enterprise Product'
		dataType: string
		lineageTag: f8a02c01-e9b6-453c-9077-30305cd2dcd9
		summarizeBy: none
		sourceColumn: Github Enterprise Product

		annotation SummarizationSetBy = Automatic

	column 'Release Series'
		dataType: string
		lineageTag: a1b9fa06-22bd-40e9-801c-a91ad93cdab0
		summarizeBy: none
		sourceColumn: Release Series

		annotation SummarizationSetBy = Automatic

	column 'Github Login'
		dataType: string
		lineageTag: bf23e472-adfe-48c3-8606-682d7e6f519c
		summarizeBy: none
		sourceColumn: Github Login

		annotation SummarizationSetBy = Automatic

	column 'Is User Flagged Spammy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 124c8075-85b4-4b74-90bc-43f3d5cd6d41
		summarizeBy: none
		sourceColumn: Is User Flagged Spammy

		annotation SummarizationSetBy = Automatic

	column 'Program Type Education'
		dataType: string
		lineageTag: d2f841a7-9a66-4d6f-8d5f-f84f78d9d980
		summarizeBy: none
		sourceColumn: Program Type Education

		annotation SummarizationSetBy = Automatic

	column 'Github Plan'
		dataType: string
		lineageTag: bceef8e1-e183-41fb-bfd6-6c91562a8c12
		summarizeBy: none
		sourceColumn: Github Plan

		annotation SummarizationSetBy = Automatic

	column 'External Resource'
		dataType: string
		lineageTag: 0df7a3b1-ce70-4343-ae42-b186cbda6376
		summarizeBy: none
		sourceColumn: External Resource

		annotation SummarizationSetBy = Automatic

	column 'Created Time Hour'
		dataType: int64
		formatString: 0
		lineageTag: 16d265be-9168-440f-bbdd-6ad1bb137dd8
		summarizeBy: sum
		sourceColumn: Created Time Hour

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Is Incident'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ed7c02bd-3a23-441f-94ce-418a03787708
		summarizeBy: none
		sourceColumn: Is Incident

		annotation SummarizationSetBy = Automatic

	column 'Reporting Flag'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0661810a-0382-446a-9f2e-77ad3f4ac8f5
		summarizeBy: none
		sourceColumn: Reporting Flag

		annotation SummarizationSetBy = Automatic

	column 'Is Escalated'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 57188f99-2560-401f-be6a-ea91b9eb497e
		summarizeBy: none
		sourceColumn: Is Escalated

		annotation SummarizationSetBy = Automatic

	column 'Is Signed In User True'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 38657266-db53-4e3e-b883-8aad11c8d3df
		summarizeBy: none
		sourceColumn: Is Signed In User True

		annotation SummarizationSetBy = Automatic

	column 'Dotcom Form Flavor'
		dataType: string
		lineageTag: 01f45faf-a830-4d80-a98e-73818aae3f10
		summarizeBy: none
		sourceColumn: Dotcom Form Flavor

		annotation SummarizationSetBy = Automatic

	column 'Is Auto Solved'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cea00b75-70d8-4c6e-b804-2b00cbe3f45a
		summarizeBy: none
		sourceColumn: Is Auto Solved

		annotation SummarizationSetBy = Automatic

	column 'Ticket Subject'
		dataType: string
		lineageTag: 2692e768-e1c8-47be-beb0-fa558a42359a
		summarizeBy: none
		sourceColumn: Ticket Subject

		annotation SummarizationSetBy = Automatic

	column 'Deflection Category Name'
		dataType: string
		lineageTag: 8099bddd-b2bc-4504-948c-fe6617f2f63e
		summarizeBy: none
		sourceColumn: Deflection Category Name

		annotation SummarizationSetBy = Automatic

	column 'Deflection Category Reference'
		dataType: string
		lineageTag: 1a92d9d8-7870-447a-8030-49e27e944a97
		summarizeBy: none
		sourceColumn: Deflection Category Reference

		annotation SummarizationSetBy = Automatic

	column 'Is Paid Customer'
		dataType: string
		lineageTag: 0c85e662-266c-43e9-a0da-eb7d30135e9c
		summarizeBy: none
		sourceColumn: Is Paid Customer

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 4aaa114c-09e1-4f7a-b7c4-bac2d403f2e6
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column 'Billed Via Billing Platform'
		dataType: string
		lineageTag: e30fdfed-2654-4f03-8279-5ee7f6ce371e
		summarizeBy: none
		sourceColumn: Billed Via Billing Platform

		annotation SummarizationSetBy = Automatic

	column 'Final  Support Plan At Ticket Open'
		dataType: string
		lineageTag: 3d91a08f-20c2-4198-add0-b03db4cbeb57
		summarizeBy: none
		sourceColumn: Final  Support Plan At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Final Support Plan Source At Ticket Open'
		dataType: string
		lineageTag: 6d43a5ae-486e-49af-9af7-655edd579747
		summarizeBy: none
		sourceColumn: Final Support Plan Source At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'License ARR A Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 18b20d8d-0f9e-4d84-9e65-77c1712af3b4
		summarizeBy: sum
		sourceColumn: License ARR A Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Support ARR At Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: fe964305-5761-4b7f-b0e8-5ee7c19b2c1d
		summarizeBy: sum
		sourceColumn: Support ARR At Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Proxy For Total Support ARR GH Plus MSFT At Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: e6f76590-0837-4dbc-b629-abdfe734d3d6
		summarizeBy: sum
		sourceColumn: Proxy For Total Support ARR GH Plus MSFT At Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Azure Category Spend At Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: caca61b6-1172-462c-82fe-f459545c2a0e
		summarizeBy: sum
		sourceColumn: Azure Category Spend At Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Mapped Support Plan At Ticket Open'
		dataType: string
		lineageTag: 7fc4cec5-619d-4fd1-b143-5ec6eb7cfa41
		summarizeBy: none
		sourceColumn: Mapped Support Plan At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Is License MS Paper At Ticket Open'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 210d9f63-e0f8-440b-9e30-57d3c6c57293
		summarizeBy: none
		sourceColumn: Is License MS Paper At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Is Customer Support Entitlement On MS Paper At Ticket Open'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 50d085a9-8eb2-4443-a8c0-2fb841dd77a3
		summarizeBy: none
		sourceColumn: Is Customer Support Entitlement On MS Paper At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Actions Billed Dollars At Ticket Open'
		dataType: int64
		formatString: 0
		lineageTag: a1736d33-4c55-4c67-bd41-a185bb16623c
		summarizeBy: sum
		sourceColumn: Actions Billed Dollars At Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Codespaces Billed Dollars At Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 3b71b069-f7fe-4883-bc0c-9cd67fedf754
		summarizeBy: sum
		sourceColumn: Codespaces Billed Dollars At Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Packages Billed Dollars at Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 09e60c43-489c-4e60-839f-423b555578dc
		summarizeBy: sum
		sourceColumn: Packages Billed Dollars at Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Shared Storage Billed Dollars At Ticket Open'
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: cf7a5845-1e65-4b37-a151-fdccbae78108
		summarizeBy: sum
		sourceColumn: Shared Storage Billed Dollars At Ticket Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column 'Is Exec Sponsor at Ticket Open'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 08d65a82-b8c0-4aef-a32e-5f9b7b2541bc
		summarizeBy: none
		sourceColumn: Is Exec Sponsor at Ticket Open

		annotation SummarizationSetBy = Automatic

	column 'Offering Type'
		dataType: string
		lineageTag: 70aca8e7-ad75-454c-8747-468ff1fb0ef5
		summarizeBy: none
		sourceColumn: Offering Type

		annotation SummarizationSetBy = Automatic

	partition DimTicket-b9e82b65-0ce3-4744-811e-4d5025e9d3fe = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_ticket_dim#(lf)| join kind=leftouter (#(lf)    database(""service_cs_analytics"").supportv3_ticket_fact#(lf)    | project ticket_id, created_date#(lf)) on ticket_id#(lf)| where is_support_team == 'TRUE'#(lf)    and is_support_squad == 'TRUE'#(lf)    and created_date >= datetime(2022-01-01)#(lf)| extend#(lf)    complexity_level_number = case(#(lf)        complexity_level == ""level_1"", 1,#(lf)        complexity_level == ""level_2"", 2,#(lf)        complexity_level == ""level_3"", 3,#(lf)        complexity_level == ""level_no_investigation"", 0,#(lf)        isempty(complexity_level), 0,#(lf)        0#(lf)    ),#(lf)    license_arr_at_ticket_open = tolong(license_arr_at_ticket_open),#(lf)    support_arr_at_ticket_open = tolong(support_arr_at_ticket_open),#(lf)    proxy_for_total_support_arr_gh_plus_msft_at_ticket_open = tolong(proxy_for_total_support_arr_gh_plus_msft_at_ticket_open),#(lf)    azure_category_spend_at_ticket_open = tolong(azure_category_spend_at_ticket_open),#(lf)    actions_billed_dollars_at_ticket_open = tolong(actions_billed_dollars_at_ticket_open),#(lf)    codespaces_billed_dollars_at_ticket_open = tolong(codespaces_billed_dollars_at_ticket_open),#(lf)    packages_billed_dollars_at_ticket_open = tolong(packages_billed_dollars_at_ticket_open),#(lf)    shared_storage_billed_dollars_at_ticket_open = tolong(shared_storage_billed_dollars_at_ticket_open)#(lf)| project#(lf)    [""Ticket ID""] = ticket_id,#(lf)    [""Status""] = status,#(lf)    [""Current Priority""] = current_priority,#(lf)    [""First Priority""] = iif(first_priority == """", ""(Blank)"", first_priority),#(lf)    [""Max Priority Set by Agent""] =  iif(max_priority_set_agent == """", ""(Blank)"", max_priority_set_agent),#(lf)    [""Max Priority Set by User""] =  iif(max_priority_set_user == """", ""(Blank)"", max_priority_set_user),#(lf)    [""Priority At Creation""] = priority_at_creation,#(lf)    [""Priority At Assigned""] = priority_at_assigned,#(lf)    [""Priority at Solved""] =  iif(priority_at_solved == """", ""(Blank)"", priority_at_solved),#(lf)    [""Spammy Reason""] = spammy_reason,#(lf)    [""Is  Initial Response Eligible""] = is_initial_response_eligible,#(lf)    [""Is Initial Response Met""] = met_initial_response,#(lf)    [""Is Ticket Follow up""] = is_ticket_follow_up,#(lf)    [""Initial Response Type""] = initial_response_type,#(lf)    [""Public Replies Count""] = public_replies,#(lf)    [""Group Stations""] = group_stations,#(lf)    [""Assignee Stations""] = assignee_stations,#(lf)    [""Reopens Count""] = reopens,#(lf)    [""Is Health Check""] = is_health_check,#(lf)    [""Is Virtual Agent""] = is_virtual_agent,#(lf)    [""Complexity Level""] = iif(complexity_level == """", ""(Blank)"", complexity_level),#(lf)    [""Complexity Level  Number""] = complexity_level_number,#(lf)    [""Is Auto Triaged""] = is_auto_triaged,#(lf)    [""Preferred Language""] = preferred_language,#(lf)    [""Education User Type""] = education_user_type,#(lf)    [""Education Subject""] = education_subject,#(lf)    [""Platform""] = platform,#(lf)    [""Global Region""] = global_region,#(lf)    [""Plan Type""] = plan_type,#(lf)    [""Github Org Plan""] = github_org_plan,#(lf)    [""Github Org Plan Rollup""] = github_org_plan_rollup,#(lf)    [""Github Enterprise Product Group""] = github_enterprise_product_group,#(lf)    [""Github Business Line Rollup""] = github_business_line_rollup,#(lf)    [""Github Enterprise Product""] = iif(github_enterprise_product == """", ""(Blank)"", github_enterprise_product),#(lf)    [""Release Series""] = release_series,#(lf)    [""Github Login""] = github_login,#(lf)    [""Is User Flagged Spammy""] = user_flagged_spammy,#(lf)    [""Program Type Education""] = program_type_education,#(lf)    [""Github Plan""] = github_plan,#(lf)    [""External Resource""] = external_resource,#(lf)    [""Created Time Hour""] = created_time_hour,#(lf)    [""Is Incident""] = is_incident,#(lf)    [""Reporting Flag""] = reporting_flag,#(lf)    [""Is Escalated""] = is_escalated,#(lf)    [""Is Signed In User True""] = signed_in_user_true,#(lf)    [""Dotcom Form Flavor""] = dotcom_form_flavor,#(lf)    [""Is Auto Solved""] = auto_solved_flag,#(lf)    [""Ticket Subject""] = subject,#(lf)    [""Deflection Category Name""] = deflection_category_name,#(lf)    [""Deflection Category Reference""] = deflection_category_reference,#(lf)    [""Is Paid Customer""] = is_paid_customer,#(lf)    [""Company""] = company,#(lf)    [""Billed Via Billing Platform""] = billed_via_billing_platform,#(lf)    [""Final  Support Plan At Ticket Open""] = final_support_plan_at_ticket_open,#(lf)    [""Final Support Plan Source At Ticket Open""] = final_support_plan_source_at_ticket_open,#(lf)    [""License ARR A Ticket Open""] = license_arr_at_ticket_open,#(lf)    [""Support ARR At Ticket Open""] = support_arr_at_ticket_open,#(lf)    [""Proxy For Total Support ARR GH Plus MSFT At Ticket Open""] = proxy_for_total_support_arr_gh_plus_msft_at_ticket_open,#(lf)    [""Azure Category Spend At Ticket Open""] = azure_category_spend_at_ticket_open,#(lf)    [""Mapped Support Plan At Ticket Open""] = mapped_support_plan_at_ticket_open,#(lf)    [""Is License MS Paper At Ticket Open""] = is_license_ms_paper_at_ticket_open,#(lf)    [""Is Customer Support Entitlement On MS Paper At Ticket Open""] = is_customer_support_entitlement_on_ms_paper_at_ticket_open,#(lf)    [""Actions Billed Dollars At Ticket Open""] = actions_billed_dollars_at_ticket_open,#(lf)    [""Codespaces Billed Dollars At Ticket Open""] = codespaces_billed_dollars_at_ticket_open,#(lf)    [""Packages Billed Dollars at Ticket Open""] = packages_billed_dollars_at_ticket_open,#(lf)    [""Shared Storage Billed Dollars At Ticket Open""] = shared_storage_billed_dollars_at_ticket_open,#(lf)    [""Is Exec Sponsor at Ticket Open""] = is_exec_sponsor_at_ticket_open,#(lf)    [""Offering Type""] = offering_type", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"License ARR A Ticket Open", Currency.Type}, {"Support ARR At Ticket Open", Currency.Type}, {"Proxy For Total Support ARR GH Plus MSFT At Ticket Open", Currency.Type}, {"Azure Category Spend At Ticket Open", Currency.Type}, {"Codespaces Billed Dollars At Ticket Open", Currency.Type}, {"Packages Billed Dollars at Ticket Open", Currency.Type}, {"Shared Storage Billed Dollars At Ticket Open", Currency.Type}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

