table EnvironmentConfig
	excludeFromModelRefresh
	lineageTag: b86571ca-d190-41b0-b8ee-7d821474fbf5

	column Environment
		dataType: string
		lineageTag: d466e2df-3488-4d67-8125-a3d9097f65a5
		summarizeBy: none
		sourceColumn: Environment

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'URL Name'
		dataType: string
		lineageTag: 1b534461-2ba4-4858-bf68-b21369e3eea6
		summarizeBy: none
		sourceColumn: URL Name

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column URL
		dataType: string
		lineageTag: 2c2d5539-e982-4525-ab9b-5b00cd8c9191
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	partition EnvironmentConfig = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/EnvironmentConfig.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Environment", type text}, {"URL Name", type text}, {"URL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS","OBJECTS_WITH_NO_DESCRIPTION"]}

