table 'Fact_P+ net-new accounts'
	lineageTag: f8f0cdec-c333-473b-b4bd-db9845e59d28

	column closing_month
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: b3c4d80b-e6ac-4001-96e5-afd36749ee21
		summarizeBy: none
		sourceColumn: closing_month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column new_accounts
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8b065e09-4523-4b67-8e77-d26be0cf65de
		summarizeBy: sum
		sourceColumn: new_accounts

		annotation SummarizationSetBy = Automatic

	partition 'Fact_P+ net-new accounts' = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("https://gh-analytics.eastus.kusto.windows.net/", "snapshots_all", "let temp = github_mysql1_issues#(lf)| join kind=inner github_mysql1_issues_labels on $left.id == $right.issue_id#(lf)| join kind=inner github_mysql1_labels on $left.label_id == $right.id#(lf)| where repository_id == '103358329'#(lf)| where label_name like 'Sales-Handoff'#(lf)| where state like 'closed'#(lf)| extend closing_month_year = format_datetime(closed_at, ""yyyy-MM"")#(lf)| summarize new_accounts = dcount(id) by closing_month_year#(lf)| order by closing_month_year;#(lf)temp#(lf)| extend closing_month = todatetime(strcat(closing_month_year, '-01'))#(lf)| project closing_month, new_accounts#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"closing_month", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

