table FactFCPMonthlyTeamForecast
	lineageTag: 7e189519-8266-4c94-875b-3fe26a8c01b4

	column monthly_team_forecast_id
		dataType: string
		lineageTag: 20d56b76-de94-4606-a797-16d3c076a305
		summarizeBy: none
		sourceColumn: monthly_team_forecast_id

		annotation SummarizationSetBy = Automatic

	column team_month_id
		dataType: string
		lineageTag: ef19d69b-34af-4be3-9dc9-5f7b6c1a7778
		summarizeBy: none
		sourceColumn: team_month_id

		annotation SummarizationSetBy = Automatic

	column team_id
		dataType: string
		isHidden
		lineageTag: 9b0e54e1-ca67-457c-a5bf-e9485754338a
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 67639222-341b-406f-b13f-6e15e337fde7
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tickets Forecasted'
		dataType: double
		lineageTag: 638a53cf-b950-4ac1-ac63-aab4182751a0
		summarizeBy: sum
		sourceColumn: Tickets Forecasted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Run Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ca43503-8cc4-420f-84f7-a68dc0bffe4e
		summarizeBy: none
		sourceColumn: Forecast Run Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column squad_id
		dataType: string
		isHidden
		lineageTag: 3475c7b7-b1b2-4635-a59b-18c1582d0234
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: string
		isHidden
		lineageTag: d8c85046-67be-47a2-9e07-0b1672e1b7f0
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Start Date' = ```
			
			DATE ( YEAR ( FactFCPMonthlyTeamForecast[Month]), MONTH ( FactFCPMonthlyTeamForecast[Month] ), 1 ) 
			```
		isHidden
		formatString: General Date
		lineageTag: 3ae563b1-f883-476e-91c7-56e82718ee68
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column forecast_lock_type
		dataType: string
		lineageTag: b36289e0-a611-4db3-8bed-99b0d305cc55
		summarizeBy: none
		sourceColumn: forecast_lock_type

		annotation SummarizationSetBy = Automatic

	partition FactFCPMonthlyTeamForecast = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_fcp_monthly_team_forecast_fact#(lf)| join kind=leftouter (#(lf)    database(""service_cs_analytics"").supportv3_fcp_forecast_dim#(lf)    | project forecast_id, forecast_lock_type#(lf)) on forecast_id#(lf)| project#(lf)    monthly_team_forecast_id,#(lf)    team_month_id,#(lf)    team_id,#(lf)    month,#(lf)    tickets_forecasted,#(lf)    forecast_lock_type#(lf)    | where toupper(trim("" "", forecast_lock_type)) == ""THREE_MONTH_LOCK""", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"month", "Month"}, {"tickets_forecasted", "Tickets Forecasted"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", FactTicketForecastOutput}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Appended Query",{{"Month", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

