table FactServerInstallations
	lineageTag: d22986b3-6218-4c3c-8891-dc8ca79195e8

	column installation_id
		dataType: double
		isHidden
		formatString: 0
		lineageTag: 6725c06f-e02e-4717-9208-a5c9fbda8247
		summarizeBy: none
		sourceColumn: installation_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","MARK_PRIMARY_KEYS"]}

	column 'Server Installation Created Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 4eef8afb-6aa6-4575-a45a-2a8fe300a11b
		summarizeBy: none
		sourceColumn: Server Installation Created Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Server Installation Updated Date'
		dataType: string
		lineageTag: 23c5dbbb-f7ff-417e-af04-805182b4633e
		summarizeBy: none
		sourceColumn: Server Installation Updated Date

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh At'
		dataType: dateTime
		formatString: General Date
		lineageTag: fb27078e-4be1-472d-a5c3-ee982f9af56c
		summarizeBy: none
		sourceColumn: Last Refresh At

		annotation SummarizationSetBy = Automatic

	partition FactServerInstallations-7db9474b-55c4-48f9-81e5-89c16b890359 = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_server_installations_fact#(lf)| project #(lf)    installation_id,#(lf)    [""Server Installation Created Date""] = created_date,#(lf)    [""Server Installation Updated Date""] = updated_date,#(lf)    [""Last Refresh At""] = dag_last_run_at", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Last Refresh At", type datetimezone}, {"Server Installation Created Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

