table FactProductArr
	lineageTag: 92ee823e-5940-43bd-b49b-dd30646a8c55

	column day
		dataType: dateTime
		formatString: Long Date
		lineageTag: a8519c94-2d6b-48bd-82b1-b3467b36be53
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Account ID'
		dataType: string
		lineageTag: f0210f44-f6b5-4f28-a526-2a8dfe3a0450
		summarizeBy: none
		sourceColumn: Account ID

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: e5f20e23-1965-4d98-b03b-6c2e87ee05c9
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 061ecce4-167f-444f-9527-75adec836f9e
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 6922fb8f-979c-41e5-8933-5c4050a35686
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'License ARR'
		dataType: double
		lineageTag: 6ba36096-f6ec-4faa-810d-b822fb519e0c
		summarizeBy: sum
		sourceColumn: License ARR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Support ARR'
		dataType: double
		lineageTag: bc84357c-60ab-4110-b11f-ca566bf0f8e0
		summarizeBy: sum
		sourceColumn: Support ARR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total ARR'
		dataType: double
		lineageTag: d151342e-0778-458e-8383-f687b186f446
		summarizeBy: sum
		sourceColumn: Total ARR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'License Seats'
		dataType: double
		lineageTag: a3e1071c-5134-4ebf-b8da-b354a4377646
		summarizeBy: sum
		sourceColumn: License Seats

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: double
		lineageTag: 31e242e7-c831-4b57-80fe-cde8c314c89b
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactProductArr = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let max_date = toscalar( #(lf)     database(""service_cs_analytics"").product_arr #(lf)     | summarize max(day) #(lf)); #(lf)database(""service_cs_analytics"").product_arr #(lf)| where day == max_date #(lf)| project #(lf)     [""Account ID""] = account_id, #(lf)     [""Product Type""] = product_type, #(lf)     [""Product Name""] = product, #(lf)     [""Type""] = type, #(lf)     [""License ARR""] = license_arr, #(lf)     [""Support ARR""] = support_arr, #(lf)     [""Total ARR""] = total_arr, #(lf)     [""License Seats""] = license_seats, #(lf)     [""Quantity""] = quantity, #(lf)     day ", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				        #"Changed Type" = Table.TransformColumnTypes(Source,{{"day", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

