table FactMonthlyEscalationsCount
	lineageTag: 8c6df87a-75db-4841-8c15-cff84d64e668

	column 'Team ID'
		dataType: string
		lineageTag: ea039c50-6f8b-4e30-8c75-aea81ed69927
		summarizeBy: none
		sourceColumn: Team ID

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column 'Escalation Count'
		dataType: int64
		formatString: 0
		lineageTag: acc18e1b-2478-42ad-b0e5-ac6096932ae5
		summarizeBy: sum
		sourceColumn: Escalation Count

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Snapshot Date'
		dataType: dateTime
		formatString: M/D/YYYY
		lineageTag: f036466d-5e1a-4338-bc4f-2ca600584961
		summarizeBy: none
		sourceColumn: Snapshot Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS","DATECOLUMN_FORMATSTRING"]}

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Squad ID'
		dataType: string
		isHidden
		lineageTag: ac23f03a-c732-4bc7-b00a-99cba03f880e
		summarizeBy: none
		sourceColumn: Squad ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Region ID'
		dataType: string
		lineageTag: 4bc4e7a3-3187-4ad9-84f2-3cadb035a60d
		summarizeBy: none
		sourceColumn: Region ID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: d25ba08d-0c9c-41b8-b177-a499e31208c9
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Month Year'
		dataType: string
		lineageTag: 01efb76f-c589-49cc-90d5-2dad5497bd63
		summarizeBy: none
		sourceColumn: Month Year

		annotation SummarizationSetBy = Automatic

	partition FactMonthlyEscalationsCount = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_monthly_escalation_all_dimensions#(lf)| project #(lf)    ['Month Year'] = month_year,#(lf)    ['Team ID'] = team_id,#(lf)    ['Squad ID'] = squad_id,#(lf)    ['Region ID'] = region_id,#(lf)    ['Product ID'] = iff(isnull(product_id), ""0"", product_id),#(lf)    ['Escalation Count'] = escalation_count,#(lf)    ['Snapshot Date'] = snapshot_date#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Snapshot Date", type date}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

