table FactICPR
	lineageTag: ed892eae-a7fe-4bde-b294-f87a476693fe

	measure 'PR Count' = ```
			
			CALCULATE (
			    COUNT ( FactICPR[pr_id] ),
			    USERELATIONSHIP ( FactICPR[Pull Request Created Date], CalendarDate[Date] )
			)
			
			```
		formatString: 0
		lineageTag: d9813dde-0954-4282-9984-a1730dc7fa6b

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure 'Pull Request Replies Count' = ```
			
			COUNT ( FactICPR[Pull Request Replies] )
			
			```
		formatString: #,0
		lineageTag: 03b31b18-18ff-41c1-8485-8193f9b646b5

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column pr_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bcb9d228-1166-4a15-895e-150f757c768f
		summarizeBy: none
		sourceColumn: pr_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column repository_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 918d3b6e-ca4c-4e25-9177-21e0d84c2535
		summarizeBy: none
		sourceColumn: repository_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column user_dotcom_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 809c80ff-8154-4598-97db-072283875457
		summarizeBy: none
		sourceColumn: user_dotcom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Pull Request Created Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: b472fca2-c52a-42c4-a254-62af16ed6034
		summarizeBy: none
		sourceColumn: Pull Request Created Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pull Request Closed Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cf09838-18ee-463a-86ef-4192d69a1655
		summarizeBy: none
		sourceColumn: Pull Request Closed Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pull Request Replies'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6db5d0bd-8bb6-45a5-947f-4667671ce766
		summarizeBy: sum
		sourceColumn: Pull Request Replies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh At'
		dataType: string
		lineageTag: 4189c192-d2be-4075-9be6-36884393cbed
		summarizeBy: none
		sourceColumn: Last Refresh At

		annotation SummarizationSetBy = Automatic

	partition FactICPR = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "supportv3_ic_pr_fact#(lf)| project #(lf)    pr_id,#(lf)    repository_id,#(lf)    user_dotcom_id,#(lf)     [""Pull Request Created Date""] = created_at,#(lf)    [""Pull Request Closed Date""] = closed_at,#(lf)    [""Pull Request Replies""] = num_comments,#(lf)    [""Last Refresh At""] = dag_last_run_at#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Pull Request Created Date", type date}, {"Pull Request Closed Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

