table FactPremiumPlusCapacity
	lineageTag: 2ca5e760-1101-4edb-9aaf-78c9ff971926

	column 'Snapshot Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: df7d6394-6b0c-48f5-8553-bad35298610e
		summarizeBy: none
		sourceColumn: Snapshot Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Assigned CRE Account Complexity'
		dataType: double
		lineageTag: b504aa73-1213-4c43-8e06-95c3d0b57969
		summarizeBy: sum
		sourceColumn: Total Assigned CRE Account Complexity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Average CRE Complexity'
		dataType: double
		lineageTag: c0ab5150-5cc2-4ed0-88fe-039eccb27f95
		summarizeBy: sum
		sourceColumn: Average CRE Complexity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target CRE Complexity'
		dataType: int64
		formatString: 0
		lineageTag: 7ef18b75-c807-4fc8-8502-5664cd0335f3
		summarizeBy: sum
		sourceColumn: Target CRE Complexity

		annotation SummarizationSetBy = Automatic

	partition FactPremiumPlusCapacity = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").premium_plus_capacity#(lf)| project #(lf)    ['Snapshot Date'] = snapshot_date,#(lf)    ['Total Assigned CRE Account Complexity'] = total_assigned_cre_account_complexity,#(lf)    ['Average CRE Complexity'] = average_cre_complexity,#(lf)    ['Target CRE Complexity'] = target_cre_complexity", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Snapshot Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

