table FactTicketRateTeam
	lineageTag: 4b16d0f6-c8fd-45bb-a748-7ff7b121c4d4

	column 'Ticket Rate'
		dataType: double
		formatString: 0
		lineageTag: ef37e574-f98a-47ac-a394-80d92be4cde3
		summarizeBy: sum
		sourceColumn: Ticket Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Product Affiliated Team'
		dataType: string
		lineageTag: 350950df-9ad5-45c2-9924-e72c5b63f0e3
		summarizeBy: none
		sourceColumn: Product Affiliated Team

		annotation SummarizationSetBy = Automatic

	column 'Team ID'
		dataType: string
		lineageTag: e7bc555d-df7e-4928-96dc-aa7cd37209a9
		summarizeBy: none
		sourceColumn: Team ID

		annotation SummarizationSetBy = Automatic

	column 'Ticket Count'
		dataType: int64
		formatString: 0
		lineageTag: 8ae5c11c-dd56-42aa-82d0-bc574ce88e9b
		summarizeBy: sum
		sourceColumn: Ticket Count

		annotation SummarizationSetBy = Automatic

	column 'Avg User-Seat'
		dataType: int64
		formatString: #,0
		lineageTag: 86f4101a-07f6-46f6-a0ac-15c18a48fd42
		summarizeBy: average
		sourceColumn: Avg User-Seat

		annotation SummarizationSetBy = User

	column 'First of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bf3ebf52-6c8f-45b0-b0f3-98109388bd92
		summarizeBy: none
		sourceColumn: First of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactTicketRateTeam = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let ticket_rate_fom = #(lf)   database('service_cs_analytics').ticket_rate_team#(lf)    | where user_count > 0 and todouble(rate) != real(null)#(lf)    | extend#(lf)        product_team = team,#(lf)        team_group = case(#(lf)            team hasprefix ""Enterprise"", ""Enterprise"",#(lf)            team hasprefix ""Technical"", ""Technical"",#(lf)            team#(lf)        ),#(lf)        first_of_month = startofmonth(todatetime(day)),#(lf)        rate_real = todouble(rate)#(lf)    | summarize #(lf)        rate = sum(rate_real),#(lf)        ticket_count = sum(ticket_count),#(lf)        avg_user = avg(user_count)#(lf)    by product_team, team_group, first_of_month#(lf)     | extend team_group = toupper(trim("" "", team_group));#(lf)ticket_rate_fom#(lf)| join kind=leftouter (#(lf)   database('service_cs_analytics').supportv3_team_dim#(lf)    | extend team_key = toupper(trim("" "", team))#(lf)    | project team_id, team_key#(lf)) on $left.team_group == $right.team_key#(lf)| project #(lf)    [""Product Affiliated Team""] = product_team,#(lf)    first_of_month,#(lf)    [""Team ID""] = team_id,#(lf)    [""Ticket Rate""] = rate,#(lf)    [""Ticket Count""] = ticket_count,#(lf)    [""Avg User-Seat""] = round(avg_user, 0)#(lf)| summarize #(lf)    [""Ticket Rate""] = sum([""Ticket Rate""])#(lf)by [""Product Affiliated Team""], [""First of Month""]=first_of_month, [""Team ID""], [""Ticket Count""], [""Avg User-Seat""]#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Avg User-Seat", Int64.Type}, {"First of Month", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

