table FactCapacityForecastOutput
	isHidden
	lineageTag: 075065a6-d9a6-4788-8a2d-3005c8ddfc7f

	column 'Forecast Run Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 818f8020-3c5c-482c-b078-a58017517cc0
		summarizeBy: none
		sourceColumn: Forecast Run Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 0731bf9f-4177-4b7c-897a-f646349aa776
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column team_id
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 71518b56-0ed2-4136-9bb6-86ca85028e07
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column squad_id
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 2aaed90b-10d4-4c1c-88f4-8cffcd62f4b4
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4ac8242e-c1ec-43b2-98e1-0ac56d914681
		summarizeBy: sum
		sourceColumn: Headcount Forecasted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted - FTE'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cdd0fb05-9320-4a5b-8ad6-2183d96ca05b
		summarizeBy: sum
		sourceColumn: Headcount Forecasted - FTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted  - XR'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fa8fafcf-fbc4-4c45-b4d5-b9e75130dcb9
		summarizeBy: sum
		sourceColumn: Headcount Forecasted  - XR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactCapacityForecastOutput = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(Lakehouse_Endpoint, "cs_analytics"),
				    dbo_capacity_forecast_output = Source{[Schema="dbo",Item="capacity_forecast_output"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_capacity_forecast_output, {"forecast_run_date", "month_end"}, CapacityForecastforLatestForecastDate, {"Latest Forecast Date", "Month"}, "CapacityForecastforLatestForecastDate", JoinKind.LeftOuter),
				    #"Expanded CapacityForecastforLatestForecastDate" = Table.ExpandTableColumn(#"Merged Queries", "CapacityForecastforLatestForecastDate", {"Latest Forecast Date"}, {"Latest Forecast Date"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded CapacityForecastforLatestForecastDate", each ([Latest Forecast Date] <> null)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"ramped_capacity", "fte_ramped_capacity", "xr_ramped_capacity", "team", "squad", "tickets_forecast", "Latest Forecast Date"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"month_end", "Month"}, {"total_headcount_forecast", "Headcount Forecasted"}, {"fte_headcount_forecast", "Headcount Forecasted - FTE"}, {"xr_headcount_forecast", "Headcount Forecasted  - XR"}, {"forecast_run_date", "Forecast Run Date"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

