table FactCallbackRequests
	lineageTag: 6e55eb96-fe2c-4e18-ab63-41ba6d70e7d9

	measure 'Average Next Reply Time in Minutes' = ```
			
			CALCULATE (
			    AVERAGE ( FactCallbackRequests[Callback Next Reply Time in Minutes] )
			)
			
			```
		formatString: #,0.00
		displayFolder: Callback Metrics
		lineageTag: 6f139e63-9619-4540-b8dd-fc3f795cc1a4

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING"]}

	measure 'Average Time to Callback Hours' = ```
			
			AVERAGEX (
			    FactCallbackRequests,
			    DIVIDE(FactCallbackRequests[Time To Callback in Seconds], 3600)
			)
			
			```
		displayFolder: Callback Metrics
		lineageTag: 397529ee-a681-4463-bbc3-f09e7fd85400

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING"]}

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Time to Callback in Seconds' = ```
			
			CALCULATE (
			    AVERAGE ( FactCallbackRequests[Time To Callback in Seconds] ) 
			)
			// average time to callback seconds you can use time to callback in seconds
			
			```
		formatString: #,0.00
		displayFolder: Callback Metrics
		lineageTag: f9791fdc-ed63-4c7c-a4a1-0d8c4f9ec502

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING"]}

	measure 'Count Callback Event ID' = ```
			
			COUNTROWS ( FactCallbackRequests )
			
			```
		formatString: #,0
		displayFolder: Callback Metrics
		lineageTag: 241aad5f-c43e-4e63-a193-849e4e9157ef

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure 'Count Callback Ticket' = ```
			
			DISTINCTCOUNT ( FactCallbackRequests[Ticket ID] )
			
			```
		formatString: #,0
		displayFolder: Callback Metrics
		lineageTag: 261e2e16-ee95-4f30-9a0d-ed8181783ad9

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column callback_event_id
		dataType: string
		isHidden
		lineageTag: 1dfd5bdd-ad8e-4479-8c37-5cd3c6a22d8e
		summarizeBy: none
		sourceColumn: callback_event_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ticket ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 14532145-a889-42ce-8a7d-58f17c62512d
		summarizeBy: none
		sourceColumn: Ticket ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Next Reply Author ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c7721d7-fa5d-45ee-83a2-85a9c3a630e0
		summarizeBy: none
		sourceColumn: Next Reply Author ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Callback Event Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: e9da5f41-d157-4858-bfb0-16f2ae1c5aec
		summarizeBy: none
		sourceColumn: Callback Event Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Callback Status Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: 49497541-b53d-4d44-9273-c747ca23ecb3
		summarizeBy: none
		sourceColumn: Callback Status Start

		annotation SummarizationSetBy = Automatic

	column 'Callback Status End'
		dataType: dateTime
		formatString: General Date
		lineageTag: f81dbdbb-3764-4f31-b74f-66914d928099
		summarizeBy: none
		sourceColumn: Callback Status End

		annotation SummarizationSetBy = Automatic

	column 'Callback Priority Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2be0acf2-7080-4bfc-90e1-072c32cbe6da
		summarizeBy: none
		sourceColumn: Callback Priority Start

		annotation SummarizationSetBy = Automatic

	column 'Callback Priority End'
		dataType: dateTime
		formatString: General Date
		lineageTag: e050ddbd-8206-4bfb-8259-166cd2a8af88
		summarizeBy: none
		sourceColumn: Callback Priority End

		annotation SummarizationSetBy = Automatic

	column 'Time To Callback in Seconds'
		dataType: int64
		formatString: 0
		lineageTag: bf0221ab-3f32-4421-a0fc-15f583aee81b
		summarizeBy: sum
		sourceColumn: Time To Callback in Seconds

		annotation SummarizationSetBy = Automatic

	column 'Callback Next Reply Time in Minutes'
		dataType: double
		lineageTag: 1d03cd36-d652-4512-92d2-89a37fdc3f59
		summarizeBy: sum
		sourceColumn: Callback Next Reply Time in Minutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Callback Next Reply Time in Seconds'
		dataType: int64
		formatString: 0
		lineageTag: c50a9672-309d-489d-ab20-ab2ee5143875
		summarizeBy: sum
		sourceColumn: Callback Next Reply Time in Seconds

		annotation SummarizationSetBy = Automatic

	partition FactCallbackRequests = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "supportv3_callback_requests_fact#(lf)| where is_in_support_team == ""TRUE""#(lf)    and is_in_support_squad == ""TRUE""#(lf)    and has_ticket_within_two_years == ""TRUE""#(lf)| project#(lf)    callback_event_id,#(lf)    [""Ticket ID""] = ticket_id,#(lf)    [""Next Reply Author ID""] = next_reply_author_id,#(lf)    [""Callback Event Date""] = callback_event_at,#(lf)    [""Callback Status Start""] = callback_status_start,#(lf)    [""Callback Status End""] = callback_status_end,#(lf)    [""Callback Priority Start""] = callback_priority_start,#(lf)    [""Callback Priority End""] = callback_priority_end,#(lf)    [""Time To Callback in Seconds""] = time_to_callback_seconds,#(lf)    [""Callback Next Reply Time in Minutes""] = next_reply_time_minutes,#(lf)    [""Callback Next Reply Time in Seconds""] = next_reply_time_seconds#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Callback Event Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

