table FactTicketRateOverall
	lineageTag: 902d30a1-9890-475c-be41-d0f63dd678f2

	column FirstOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2e8aaf50-4f4a-48e2-90f9-7ac9b6719f50
		summarizeBy: none
		sourceColumn: FirstOfMonth

		annotation SummarizationSetBy = Automatic

	column 'Ticket Rate'
		dataType: double
		lineageTag: d3ad6030-33b6-42f9-9f3a-27878591a516
		summarizeBy: sum
		sourceColumn: Ticket Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ticket Count'
		dataType: int64
		formatString: 0
		lineageTag: 415bb483-b52b-404e-83e9-f455c2a3ad21
		summarizeBy: sum
		sourceColumn: Ticket Count

		annotation SummarizationSetBy = Automatic

	column 'Avg User'
		dataType: int64
		formatString: 0
		lineageTag: 6f41e8ed-158b-4e13-a209-1ca0ec6a312c
		summarizeBy: sum
		sourceColumn: Avg User

		annotation SummarizationSetBy = Automatic

	partition FactTicketRateOverall = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let ticket_rate = #(lf)     database(""service_cs_analytics"").ticket_rate_overall#(lf)     | extend day_dt = todatetime(day)#(lf)    | extend FirstOfMonth = startofmonth(day_dt);#(lf)ticket_rate#(lf)| summarize #(lf)    TicketRate = sum(rate),#(lf)    ticket_count = sum(ticket_count),#(lf)    avg_user = avg(user_count)#(lf)    by FirstOfMonth#(lf)| project todatetime(FirstOfMonth), [""Ticket Rate""] = TicketRate, [""Ticket Count""]=ticket_count, [""Avg User""]=toint(avg_user)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FirstOfMonth", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

