table FactEscalationsIssue
	lineageTag: 4ba87029-7bcb-460c-95f4-3e7a7c7b3063

	column issue_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c5d72cc-e13a-47d6-944b-c7dbc4a8ea0f
		summarizeBy: none
		sourceColumn: issue_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Issue Number'
		dataType: int64
		formatString: 0
		lineageTag: 07a5a40e-b6af-44a6-ba52-a2c507a71c51
		summarizeBy: sum
		sourceColumn: Issue Number

		annotation SummarizationSetBy = Automatic

	column 'SLA met in Minutes'
		dataType: int64
		formatString: 0
		lineageTag: 8e083c06-48e8-4078-a70d-1598874d6a0f
		summarizeBy: sum
		sourceColumn: SLA met in Minutes

		annotation SummarizationSetBy = Automatic

	column 'First EPD Comment At'
		dataType: dateTime
		formatString: General Date
		lineageTag: 63115df1-6a7e-4ff8-a726-e971c72345e0
		summarizeBy: none
		sourceColumn: First EPD Comment At

		annotation SummarizationSetBy = Automatic

	column 'Issue Created At'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cee03bd-23af-4787-a83c-905125099c2f
		summarizeBy: none
		sourceColumn: Issue Created At

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactEscalationsIssue = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_escalations_issue_bridge #(lf)| join kind=inner ( #(lf)     database(""service_cs_analytics"").supportv3_escalations_issue_fact #(lf)     | project  #(lf)         issue_id,  #(lf)         [""Issue Number""] = issue_number,  #(lf)         [""SLA met in Minutes""] = sla_met_in_minutes,  #(lf)         [""First EPD Comment At""] = first_epd_comment_at,  #(lf)         [""Issue Created At""] = issue_created_at #(lf)) on issue_id #(lf)| where is_ticket_within_two_years == 1 #(lf)| distinct  #(lf)     issue_id,  #(lf)     [""Issue Number""],  #(lf)     [""SLA met in Minutes""],  #(lf)     [""First EPD Comment At""],  #(lf)     [""Issue Created At""] ", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Issue Created At", type date}, {"First EPD Comment At", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

