table FactTicketForecastOutput
	isHidden
	lineageTag: cc0e8ac5-6d30-4486-9fbb-334de6bd654f

	column 'Forecast Run Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: date
		lineageTag: d3ae9d4c-8ab7-4298-8a82-e08e60ff73a1
		summarizeBy: none
		sourceColumn: Forecast Run Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 290ea083-fcd5-45ac-b229-40599b0b28e3
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column team_id
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: ea23ea55-fcef-4210-aa16-649e34774452
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column squad_id
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 83df1f61-c57e-4811-bbc6-24fcfbd09b51
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: cc27f544-ae53-47de-bf83-775578b5e53d
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tickets Forecasted'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 46e2010c-c55b-4802-acf6-9ff54e43b05c
		summarizeBy: sum
		sourceColumn: Tickets Forecasted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactTicketForecastOutput = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(Lakehouse_Endpoint, "cs_analytics"),
				    dbo_ticket_forecast_output = Source{[Schema="dbo",Item="ticket_forecast_output"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_ticket_forecast_output, {"forecast_run_date", "month_end"}, TicketForecastforLatestForecastDate, {"Latest Forecast Date", "Month"}, "TicketForecastforLatestForecastDate", JoinKind.LeftOuter),
				    #"Expanded TicketForecastforLatestForecastDate1" = Table.ExpandTableColumn(#"Merged Queries", "TicketForecastforLatestForecastDate", {"Latest Forecast Date"}, {"Latest Forecast Date"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded TicketForecastforLatestForecastDate1", each ([Latest Forecast Date] <> null)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"team", "squad", "region", "Latest Forecast Date"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"month_end", "Month"}, {"tickets_forecast", "Tickets Forecasted"}, {"forecast_run_date", "Forecast Run Date"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

