table FactICIssue
	lineageTag: 2cb9d955-af34-48c2-a9e8-48af333369a6

	measure 'Github Issues Count' = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( FactICIssue[Issue ID] ),
			    USERELATIONSHIP ( FactICIssue[Github Issue Created Date], CalendarDate[Date] )
			)
			
			```
		formatString: 0
		lineageTag: fe550531-a0fb-44fd-a756-211ac02d844d

	measure 'Github Issues Replies Count' =
			
			COUNT ( FactICIssue[Issue Replies Count] )
		formatString: 0
		lineageTag: 4d95c855-79ef-41ed-918b-d36a8dacb36d

	column user_dotcom_id
		dataType: int64
		formatString: 0
		lineageTag: 54e8c634-63a3-4b17-ad6e-aad9b177c1de
		summarizeBy: none
		sourceColumn: user_dotcom_id

		annotation SummarizationSetBy = Automatic

	column 'Issue ID'
		dataType: int64
		formatString: 0
		lineageTag: c5639974-4142-488b-bc18-2f9c3b0c69b6
		summarizeBy: none
		sourceColumn: Issue ID

		annotation SummarizationSetBy = Automatic

	column 'Repository ID'
		dataType: int64
		formatString: 0
		lineageTag: ea2aebba-9dbd-423c-9f5a-9a19bde49bbb
		summarizeBy: count
		sourceColumn: Repository ID

		annotation SummarizationSetBy = Automatic

	column 'Github Issue Created Date'
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: c1eb3967-ea59-4a97-822a-8e58afd02055
		summarizeBy: none
		sourceColumn: Github Issue Created Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Github Issue Closed Date'
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: c479edc5-38fd-4f73-aa24-788716f3137c
		summarizeBy: none
		sourceColumn: Github Issue Closed Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Issue Replies Count'
		dataType: int64
		formatString: 0
		lineageTag: 201ab240-1538-4090-9169-278ae55de483
		summarizeBy: sum
		sourceColumn: Issue Replies Count

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh At'
		dataType: dateTime
		formatString: General Date
		lineageTag: f177719e-3bea-4654-a8aa-716c0adac702
		summarizeBy: none
		sourceColumn: Last Refresh At

		annotation SummarizationSetBy = Automatic

	partition FactICIssue = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "supportv3_ic_issue_fact#(lf)| project #(lf)    [""Issue ID""]=issue_id,#(lf)    user_dotcom_id,#(lf)    [""Repository ID""]=repository_id,#(lf)    [""Github Issue Created Date""]=issue_created_at,#(lf)    [""Github Issue Closed Date""]=issue_closed_at,#(lf)    [""Issue Replies Count""]=issue_comment_count,#(lf)    [""Last Refresh At""]=dag_last_run_at", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Github Issue Created Date", type date}, {"Github Issue Closed Date", type date}, {"Last Refresh At", type datetimezone}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

