table FactCRECustomerMonthlySummary
	lineageTag: e9784782-0dcb-446e-bd88-33f02acd686f

	column salesforce_account_id
		dataType: string
		isHidden
		lineageTag: f48ebf87-c40a-4138-9407-932b4ddcbf83
		summarizeBy: none
		sourceColumn: salesforce_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 390c647e-fc27-4b45-aef2-21984be0003c
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column zendesk_user_id_cre_1
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d98e4f0-30bd-4a8b-a55b-e55594905883
		summarizeBy: sum
		sourceColumn: zendesk_user_id_cre_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column zendesk_user_id_cre_2
		dataType: int64
		formatString: 0
		lineageTag: 6423035a-6cf7-4ce0-8be9-d3ea42eda1af
		summarizeBy: sum
		sourceColumn: zendesk_user_id_cre_2

		annotation SummarizationSetBy = Automatic

	column 'Overall Level of Effort'
		dataType: string
		lineageTag: 8fef76b1-d9b6-4fe8-962f-f592f51c81b3
		summarizeBy: none
		sourceColumn: Overall Level of Effort

		annotation SummarizationSetBy = Automatic

	column 'CRE Summary Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e88bca8e-fbdb-4a6d-b033-0c114836d5ba
		summarizeBy: none
		sourceColumn: CRE Summary Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Sentiment'
		dataType: string
		lineageTag: 24770128-352e-4033-9c44-801c7d05603a
		summarizeBy: none
		sourceColumn: Customer Sentiment

		annotation SummarizationSetBy = Automatic

	column 'Customer Sentiment Number'
		dataType: int64
		formatString: 0
		lineageTag: 82b375c9-1ea3-4905-b579-f25c4e6a2bbd
		summarizeBy: sum
		sourceColumn: Customer Sentiment Number

		annotation SummarizationSetBy = Automatic

	column 'Total Technical Advisory Hours Used'
		dataType: double
		formatString: #,0.00
		lineageTag: 71862149-374a-4682-88e8-a087fd86bb99
		summarizeBy: sum
		sourceColumn: Total Technical Advisory Hours Used

		annotation SummarizationSetBy = Automatic

	column 'Overall Level of Effort Number'
		dataType: int64
		formatString: 0
		lineageTag: d18799f5-b298-454d-98ac-a5100421d804
		summarizeBy: sum
		sourceColumn: Overall Level of Effort Number

		annotation SummarizationSetBy = Automatic

	partition FactCRECustomerMonthlySummary = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let CRECustomerMonthlySummary = #(lf)    supportv3_cre_customer_monthly_summary_fact#(lf)    | project #(lf)        salesforce_account_id,#(lf)        id,#(lf)        zendesk_user_id_cre_1,#(lf)        zendesk_user_id_cre_2,#(lf)        ['Overall Level of Effort'] = overall_level_of_effort_acccount,#(lf)        ['CRE Summary Date'] = cre_summary_date,#(lf)        ['Customer Sentiment'] = customer_sentiment,#(lf)        ['Customer Sentiment Number'] = tolong(substring(customer_sentiment, 0, 1)),#(lf)        ['Total Technical Advisory Hours Used'] = todouble(total_technical_advisory_hours_used)#(lf)    | extend #(lf)        ['Overall Level of Effort Number'] = tolong(split(['Overall Level of Effort'], "" "")[0])#(lf)    ;#(lf)    CRECustomerMonthlySummary", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CRE Summary Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

