table FactCapacityForecastTeamRegionOutput
	lineageTag: c55d8afe-dadf-4ceb-acc4-ffcaba2d0653

	column 'Forecast Run Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 32f01ffd-4750-43cc-93a4-f1319f0da7c0
		summarizeBy: none
		sourceColumn: Forecast Run Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month End'
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 2aad0ac5-c610-403f-807e-f9214841dbb4
		summarizeBy: none
		sourceColumn: Month End

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Team ID'
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 610d1b33-e8e6-435c-9f74-fe6c3abd4d61
		summarizeBy: none
		sourceColumn: Team ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Region ID'
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 0d8f4b61-2ab2-4ea5-8dc6-e55510d6d41a
		summarizeBy: none
		sourceColumn: Region ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted - Overall - Region'
		dataType: double
		formatString: 0
		sourceProviderType: float
		lineageTag: f32c6f08-b87c-4fa2-9e87-f630fa9afd85
		summarizeBy: sum
		sourceColumn: Headcount Forecasted - Overall - Region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Headcount Forecasted - FTE'
		dataType: double
		formatString: 0.00
		sourceProviderType: float
		lineageTag: e68cf286-f42e-479f-ad7f-4de87f180c18
		summarizeBy: sum
		sourceColumn: Headcount Forecasted - FTE

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted - XR'
		dataType: double
		formatString: 0
		sourceProviderType: float
		lineageTag: 83dc029b-dfcd-49b8-bee4-d89abb0faff6
		summarizeBy: sum
		sourceColumn: Headcount Forecasted - XR

		annotation SummarizationSetBy = Automatic

	partition FactCapacityForecastTeamRegionOutput = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(Lakehouse_Endpoint, "cs_analytics"),
				    dbo_capacity_forecast_team_region_output = Source{[Schema="dbo",Item="capacity_forecast_team_region_output"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_capacity_forecast_team_region_output,{"team", "region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"team_id", "Team ID"}, {"forecast_run_date", "Forecast Run Date"}, {"month_end", "Month End"}, {"region_id", "Region ID"}, {"total_headcount_forecast", "Headcount Forecasted"}, {"fte_headcount_forecast", "Headcount Forecasted - FTE"}, {"xr_headcount_forecast", "Headcount Forecasted - XR"}, {"ramped_capacity", "Ramped Capacity"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Forecast Run Date", "Month End"}, CapacityForecastRegionLatestForecastDate, {"Latest Forecast Date", "month_end"}, "TicketForecastforLatestForecastDate", JoinKind.LeftOuter),
				    #"Expanded TicketForecastforLatestForecastDate" = Table.ExpandTableColumn(#"Merged Queries", "TicketForecastforLatestForecastDate", {"Latest Forecast Date"}, {"TicketForecastforLatestForecastDate.Latest Forecast Date"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Expanded TicketForecastforLatestForecastDate", each ([TicketForecastforLatestForecastDate.Latest Forecast Date] <> null)),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"Ramped Capacity"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"TicketForecastforLatestForecastDate.Latest Forecast Date", "Latest Forecast Date"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"Latest Forecast Date"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"Headcount Forecasted", "Headcount Forecasted - Overall - Region"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

