table FactTicket
	lineageTag: 77479ed5-178a-4e55-92a5-8106fe5721cb

	measure Measure = ```
			
			DISTINCTCOUNT ( FactTicket[salesforce_account_id] )
			
			```
		formatString: #,0
		displayFolder: Foreign Keys
		lineageTag: 228d3dae-4ebf-4055-a12b-343a019e471b

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column ticket_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 81e51058-c6bc-4961-a629-c2794f78ca51
		summarizeBy: none
		sourceColumn: ticket_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","MARK_PRIMARY_KEYS"]}

	column squad_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: aa430e58-8c70-4eaf-afae-19437b451afc
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column region_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 6e23862f-f606-47d6-8b4a-5a0a4074a7d5
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column requester_zendesk_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: bf695663-789f-47bd-9473-57f669444efe
		summarizeBy: none
		sourceColumn: requester_zendesk_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column submitter_zendesk_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: e43287ea-54ac-4bcf-b232-79fb474a8385
		summarizeBy: none
		sourceColumn: submitter_zendesk_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column assignee_zendesk_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 5bc27287-f317-430f-8930-2403df55cdf3
		summarizeBy: none
		sourceColumn: assignee_zendesk_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column requester_dotcom_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: d31acb20-8604-4b17-90f8-b7ce314b2e66
		summarizeBy: none
		sourceColumn: requester_dotcom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column submitter_dotcom_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 5c063450-5300-4197-8739-3b5872b1f42b
		summarizeBy: none
		sourceColumn: submitter_dotcom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column assignee_dotcom_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 6ccbcf0c-538d-4a1f-8f7e-48a8ce62d8b1
		summarizeBy: none
		sourceColumn: assignee_dotcom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column agent_initial_response_zendesk_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 8f3da1e7-a501-4db0-b465-c402c3e0cad8
		summarizeBy: none
		sourceColumn: agent_initial_response_zendesk_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column agent_squad_assigned_1_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: b64ba866-af35-4923-81dc-64edb33bf94c
		summarizeBy: none
		sourceColumn: agent_squad_assigned_1_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column agent_squad_assigned_2_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 0c19d992-2f86-43a3-bd43-40871cbea757
		summarizeBy: none
		sourceColumn: agent_squad_assigned_2_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column organization_zendesk_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: fca51435-9732-4565-a43c-62e4ce281993
		summarizeBy: none
		sourceColumn: organization_zendesk_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column manager_dotcom_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: e3a3f259-4e0d-4759-8d0c-b269bd92c146
		summarizeBy: none
		sourceColumn: manager_dotcom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS","REMOVE_REDUNDANT_COLUMNS_IN_RELATED_TABLES"]}

	column manager_zendesk_user_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 05a24cab-c8fb-471a-a4bd-673ee8805988
		summarizeBy: none
		sourceColumn: manager_zendesk_user_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column standardized_category_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: bfeb7be1-d4a7-413c-90bf-9f77b3047bd1
		summarizeBy: none
		sourceColumn: standardized_category_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column enterprise_account_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 8ee29d28-c981-4020-aa9f-26e7d83d1e15
		summarizeBy: none
		sourceColumn: enterprise_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column parent_salesforce_account_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: b628b4f8-d8b6-4bb2-9c56-09853d692dd0
		summarizeBy: none
		sourceColumn: parent_salesforce_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column salesforce_account_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 238795fc-de13-47e4-93a0-35f408776380
		summarizeBy: none
		sourceColumn: salesforce_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column cloud_instance_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 36aa7568-3136-4afd-8957-6f4d3ab4808b
		summarizeBy: none
		sourceColumn: cloud_instance_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE"]}

	column updated_at
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 39260c26-dcb2-4696-a8b9-476edda6cd0c
		summarizeBy: none
		sourceColumn: updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column latest_comment_added_at
		dataType: dateTime
		formatString: mm/dd/yyyy
		displayFolder: Dates
		lineageTag: 48753e94-5ec3-43f1-a808-360ed33e7365
		summarizeBy: none
		sourceColumn: latest_comment_added_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column assignee_updated_at
		dataType: dateTime
		isHidden
		formatString: General Date
		displayFolder: Dates
		lineageTag: f9ebbaf4-97b7-4720-9e13-195ab86a265d
		summarizeBy: none
		sourceColumn: assignee_updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column requester_updated_at
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 9df71d57-3d5b-4841-b3ac-3fc470f7968c
		summarizeBy: none
		sourceColumn: requester_updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column status_updated_at
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 1563353f-6392-4a88-9535-5adef4e7a2d1
		summarizeBy: none
		sourceColumn: status_updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column initially_assigned_at
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: bcb8f1a9-6a2b-468d-a217-52ed9361f7b1
		summarizeBy: none
		sourceColumn: initially_assigned_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column assigned_at
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: dfbb2896-c186-4819-9ad8-1dc02a3ff678
		summarizeBy: none
		sourceColumn: assigned_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column first_reply_at_calendar_minutes
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 7bd736a4-16f5-4f65-b199-b533725e5fdd
		summarizeBy: none
		sourceColumn: first_reply_at_calendar_minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column first_reply_at_business_minutes
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 4a87c66d-67a9-44e0-91d0-b90db464d6ed
		summarizeBy: none
		sourceColumn: first_reply_at_business_minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column time_to_reply_minutes_calendar_minutes
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: e10e6a5f-7cf6-4d86-8a1c-5c141a50914f
		summarizeBy: sum
		sourceColumn: time_to_reply_minutes_calendar_minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column time_to_reply_minutes_business_minutes
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 4f81d9bd-2f72-4d33-acdd-581e44b40d68
		summarizeBy: sum
		sourceColumn: time_to_reply_minutes_business_minutes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column updated_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		displayFolder: Dates
		lineageTag: ff494963-7835-4d30-97e9-bc4da8b586c4
		summarizeBy: none
		sourceColumn: updated_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column latest_comment_added_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 9a2c7b1b-1dd2-4d89-a3bd-3256a0c140fc
		summarizeBy: none
		sourceColumn: latest_comment_added_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column assignee_updated_date
		dataType: dateTime
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 5fd8f813-048a-4c09-951d-b851036a7689
		summarizeBy: none
		sourceColumn: assignee_updated_date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column requester_updated_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 3d98763c-6d60-4a70-843d-98c8cab81f66
		summarizeBy: none
		sourceColumn: requester_updated_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column status_updated_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 19f9fa67-2f7f-4cbb-8754-870586db5362
		summarizeBy: none
		sourceColumn: status_updated_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column initially_assigned_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 925d276b-24d3-422b-a608-776c56bdcc14
		summarizeBy: none
		sourceColumn: initially_assigned_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column assigned_date
		dataType: dateTime
		formatString: Short Date
		displayFolder: Dates
		lineageTag: 97564c99-9e07-4444-bfc0-b88dd1f91a32
		summarizeBy: none
		sourceColumn: assigned_date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column reply_time_in_minutes_calendar
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: bda1ab0e-8c48-48f5-b2d1-b298327e5287
		summarizeBy: sum
		sourceColumn: reply_time_in_minutes_calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column reply_time_in_minutes_business
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 991130bf-e8da-4cfa-950d-88e2f8ac152e
		summarizeBy: sum
		sourceColumn: reply_time_in_minutes_business

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column agent_wait_time_in_minutes_calendar
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: cb0b3237-fb96-40cb-9c26-6d24fb51f347
		summarizeBy: sum
		sourceColumn: agent_wait_time_in_minutes_calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column agent_wait_time_in_minutes_business
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: c80c7c34-0327-4909-b23d-26eb4a2311de
		summarizeBy: sum
		sourceColumn: agent_wait_time_in_minutes_business

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column requester_wait_time_in_minutes_calendar
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: cd412592-2ca1-4485-978f-bafb13ccd530
		summarizeBy: sum
		sourceColumn: requester_wait_time_in_minutes_calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column requester_wait_time_in_minutes_business
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 947f74d1-3f0a-4fcd-aa8e-9485743f081e
		summarizeBy: sum
		sourceColumn: requester_wait_time_in_minutes_business

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column on_hold_time_in_minutes_business
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 843735ed-5f8a-4023-8781-b9645625e532
		summarizeBy: sum
		sourceColumn: on_hold_time_in_minutes_business

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column on_hold_time_in_minutes_calendar
		dataType: int64
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 5a78805a-ed9a-419b-86b6-3ac1b15d1373
		summarizeBy: sum
		sourceColumn: on_hold_time_in_minutes_calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Full Resolution Time in Days Calendar' = ```
			
			
			DIVIDE (
			    DIVIDE ( FactTicket[Full Resolution Time in Minutes Calendar] , 60 ),
			    24
			
			    
			
			
			)
			```
		formatString: 0
		displayFolder: Ticket Metrics
		lineageTag: 4b3905d0-89ba-4845-ad13-7b8ef3c0854a
		summarizeBy: none

		annotation SummarizationSetBy = User

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column proxima_id
		dataType: string
		lineageTag: 2df991bd-e040-4803-adb6-4d862cf4d243
		summarizeBy: none
		sourceColumn: proxima_id

		annotation SummarizationSetBy = Automatic

	column TicketAgeInDays = ```
			
			    DATEDIFF(FactTicket[Created Date], TODAY(), DAY) 
			   
			
			```
		formatString: 0
		lineageTag: 8bda09dc-b63d-4b68-966a-f700f0c4d38b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Latest_Public_Comment_Added_At = ```
			
			VAR LatestPublicComment =
			    CALCULATE(
			        SELECTEDVALUE(FactTicket[latest_comment_added_at]),
			        KEEPFILTERS(FactTicketComment[is public comment]=1)
			    )
			RETURN
			    LatestPublicComment
			
			```
		formatString: mm/dd/yyyy
		displayFolder: Dates
		lineageTag: 9fcaffd4-20ec-4e62-bcf4-db6e0f32df2e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column team_id
		dataType: string
		lineageTag: c17d78e4-c9b8-4ae5-a00b-56193a4049e8
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column 'Created At'
		dataType: dateTime
		formatString: General Date
		lineageTag: ff2b2b6b-95aa-4e97-9f53-8f36ff03e369
		summarizeBy: none
		sourceColumn: Created At

		annotation SummarizationSetBy = Automatic

	column 'Solved At'
		dataType: dateTime
		formatString: General Date
		lineageTag: ad3b1a7f-2aaf-4a73-b673-8ded6fc16c75
		summarizeBy: none
		sourceColumn: Solved At

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		formatString: MM/dd/yyyy
		lineageTag: 0f1321e2-8c4a-4654-a3ac-9d52d9d78bdf
		summarizeBy: none
		sourceColumn: Created Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Solved Date'
		dataType: dateTime
		formatString: MM/dd/yyyy
		lineageTag: 01a21fe3-b575-4e31-8e6c-21f475c9022b
		summarizeBy: none
		sourceColumn: Solved Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Reply time Initial Response'
		dataType: int64
		formatString: 0
		lineageTag: 919e8130-20e5-4cec-a501-8a66d5e310ed
		summarizeBy: sum
		sourceColumn: Reply time Initial Response

		annotation SummarizationSetBy = Automatic

	column 'Full Resolution Time in Minutes Calendar'
		dataType: int64
		formatString: 0
		lineageTag: 1733eedb-47cc-41b5-8d56-bf4bf96dda35
		summarizeBy: sum
		sourceColumn: Full Resolution Time in Minutes Calendar

		annotation SummarizationSetBy = Automatic

	column TicketAgeInHours = ```
			
			    DATEDIFF(FactTicket[Created At], NOW(), HOUR) 
			   
			
			```
		formatString: 0
		lineageTag: 18406221-1482-4306-9982-98c558ab2922
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactTicket-e8fa11b3-b787-4851-ba15-83b09992c302 = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_ticket_fact#(lf)| where is_support_team == ""TRUE""#(lf)    and is_support_squad == ""TRUE""#(lf)    and created_date >= datetime(2022-01-01)#(lf)| project#(lf)    ticket_id,#(lf)    team_id,#(lf)    squad_id,#(lf)    region_id,#(lf)    requester_zendesk_id,#(lf)    submitter_zendesk_id,#(lf)    assignee_zendesk_id,#(lf)    requester_dotcom_id,#(lf)    submitter_dotcom_id,#(lf)    assignee_dotcom_id,#(lf)    agent_initial_response_zendesk_id,#(lf)    agent_squad_assigned_1_id,#(lf)    agent_squad_assigned_2_id,#(lf)    organization_zendesk_id,#(lf)    manager_dotcom_id,#(lf)    manager_zendesk_user_id,#(lf)    standardized_category_id,#(lf)    enterprise_account_id,#(lf)    parent_salesforce_account_id,#(lf)    salesforce_account_id,#(lf)    cloud_instance_id,#(lf)    [""Created At""] = created_at,#(lf)    updated_at,#(lf)    [""Solved At""] = solved_at,                         #(lf)    assignee_updated_at,#(lf)    requester_updated_at,#(lf)    status_updated_at,#(lf)    initially_assigned_at,#(lf)    assigned_at,#(lf)    first_reply_at_calendar_minutes,#(lf)    first_reply_at_business_minutes,#(lf)    time_to_reply_minutes_calendar_minutes,#(lf)    time_to_reply_minutes_business_minutes,#(lf)    [""Created Date""] = created_date,                       #(lf)    updated_date,#(lf)    [""Solved Date""] = solved_date,#(lf)    latest_comment_added_date,#(lf)    assignee_updated_date,#(lf)    requester_updated_date,#(lf)    status_updated_date,#(lf)    initially_assigned_date,#(lf)    assigned_date,#(lf)    reply_time_in_minutes_calendar,#(lf)    reply_time_in_minutes_business,#(lf)    [""Reply time Initial Response""] = reply_time_initial_response, #(lf)    agent_wait_time_in_minutes_calendar,#(lf)    agent_wait_time_in_minutes_business,#(lf)    requester_wait_time_in_minutes_calendar,#(lf)    requester_wait_time_in_minutes_business,#(lf)    [""Full Resolution Time in Minutes Calendar""] = full_resolution_time_in_minutes_calendar,#(lf)    on_hold_time_in_minutes_business,#(lf)    on_hold_time_in_minutes_calendar,#(lf)    proxima_id,#(lf)    latest_comment_added_at#(lf)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				      #"Changed Type" = Table.TransformColumnTypes(Source,{{"updated_at", type datetime}, {"Solved At", type datetime}, {"latest_comment_added_at", type datetime}, {"Created At", type datetime}, {"assignee_updated_at", type datetime}, {"requester_updated_at", type datetime}, {"status_updated_at", type datetime}, {"initially_assigned_at", type datetime}, {"assigned_at", type datetime}, {"first_reply_at_calendar_minutes", type datetime}, {"first_reply_at_business_minutes", type datetime}, {"Created Date", type datetime}, {"updated_date", type datetime}, {"Solved Date", type datetime}, {"latest_comment_added_date", type datetime}, {"assignee_updated_date", type datetime}, {"requester_updated_date", type datetime}, {"status_updated_date", type datetime}, {"initially_assigned_date", type datetime}, {"assigned_date", type datetime}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

