table FactFCPMonthlyTeamMetrics
	lineageTag: d465537f-d182-4166-a18a-4054a63a238d

	column team_month_id
		dataType: string
		lineageTag: 524a267f-dba0-44f8-85a5-deb08e1cad4b
		summarizeBy: none
		sourceColumn: team_month_id

		annotation SummarizationSetBy = Automatic

	column team_id
		dataType: string
		isHidden
		lineageTag: 23fe822c-a75d-4e7c-825e-85e09e7cfc21
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Forecast Run Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c012132e-5e15-4987-ba9a-a9a241bce7b4
		summarizeBy: none
		sourceColumn: Forecast Run Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column squad_id
		dataType: string
		lineageTag: 2b210fb1-6244-4f15-8158-b206d2459b45
		summarizeBy: none
		sourceColumn: squad_id

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted - FTE'
		dataType: int64
		formatString: 0
		lineageTag: 7b628f4c-20e4-44c3-9976-d56e46961722
		summarizeBy: sum
		sourceColumn: Headcount Forecasted - FTE

		annotation SummarizationSetBy = Automatic

	column 'Headcount Forecasted  - XR'
		dataType: int64
		formatString: 0
		lineageTag: 0f2ab823-033c-438e-bce7-9bf33654446f
		summarizeBy: sum
		sourceColumn: Headcount Forecasted  - XR

		annotation SummarizationSetBy = Automatic

	column 'Month Start Date' =
			
			DATE ( YEAR ( FactFCPMonthlyTeamMetrics[Month] ), MONTH ( FactFCPMonthlyTeamMetrics[Month] ), 1 )
		formatString: General Date
		lineageTag: 6e59355c-c38c-4317-a3bd-bc9b76005e26
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Target Capacity Gap' = 0
		formatString: 0
		lineageTag: 8a15468b-f3d2-46e3-ba2d-0be3138a7959
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 691b01db-eab8-419b-83f9-d6f8b872a76f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Headcount Forecasted'
		dataType: double
		lineageTag: 6f715f7a-fd9f-4663-a7b1-22153737af33
		summarizeBy: sum
		sourceColumn: Headcount Forecasted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last ReFresh At'
		dataType: string
		lineageTag: 00c8162f-6a0e-495c-aa99-0fc2f80b9c18
		summarizeBy: none
		sourceColumn: Last ReFresh At

		annotation SummarizationSetBy = Automatic

	partition FactFCPMonthlyTeamMetrics = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "    database(""service_cs_analytics"").supportv3_fcp_monthly_team_metrics_fact#(lf)| project#(lf)    team_month_id,#(lf)    team_id,#(lf)    [""Month""]=month,#(lf)    [""Headcount Forecasted""]=headcount_to_support_forecast,#(lf)    [""Last ReFresh At""]=dag_last_run_at", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				      #"Appended Query" = Table.Combine({Source, FactCapacityForecastOutput}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Appended Query",{{"Month", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

