table FactTicketRateOffering
	lineageTag: 4e91ac10-cdd7-4906-bce0-a0a02839cacc

	column user_type
		dataType: string
		lineageTag: db4fd4f0-5e55-499c-a067-bc9b53a8b0b9
		summarizeBy: none
		sourceColumn: user_type

		annotation SummarizationSetBy = Automatic

	column Offering
		dataType: string
		lineageTag: 311c846f-284f-4cea-845b-fafeefb19383
		summarizeBy: none
		sourceColumn: Offering

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6035d3b0-2384-49d7-be61-199756252ba9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Ticket Count'
		dataType: int64
		formatString: 0
		lineageTag: 741fbbc4-8335-48d7-a0d4-4cea1ee3ec29
		summarizeBy: sum
		sourceColumn: Total Ticket Count

		annotation SummarizationSetBy = Automatic

	column 'Avg User Seat'
		dataType: double
		lineageTag: 9804c3b3-c07b-4480-9e39-723790a2d959
		summarizeBy: average
		sourceColumn: Avg User Seat

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ticket Rate'
		dataType: double
		lineageTag: 6869edca-c7b3-4267-941b-800ab489b7c3
		summarizeBy: sum
		sourceColumn: Ticket Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactTicketRateOffering = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "ticket_rate_offering#(lf)| where user_count > 0#(lf)    and todouble(rate) != real(null)#(lf)| extend day_dt = todatetime(day)#(lf)| extend first_of_month = startofmonth(day_dt)#(lf)| extend rate_float = todouble(rate)#(lf)| summarize #(lf)    rate = sum(rate_float),#(lf)    ticket_count = sum(ticket_count),#(lf)    avg_user = avg(user_count)#(lf)  by offering, first_of_month, user_type#(lf)| summarize #(lf)    [""Ticket Rate""] = sum(rate),#(lf)    [""Total Ticket Count""] = sum(ticket_count),#(lf)    [""Avg User Seat""] = avg(avg_user)#(lf)  by [""Offering""] = offering, [""Month""] = first_of_month, user_type", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Month", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

