table FactTicketCsatSurvey
	lineageTag: 27b233ce-73b4-4a11-b980-d5ce4fb9d363

	measure 'Customer Effort Metric' = ```
			
			AVERAGE ( FactTicketCsatSurvey[Customer Effort] )
			
			```
		formatString: #,0.00
		displayFolder: Survey Metrics
		lineageTag: ae9e55f9-dde1-451c-91e2-42c924dfdd6a

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","INTEGER_FORMATTING"]}

	column survey_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cdff29b8-ec85-49fe-8437-a481990c8106
		summarizeBy: none
		sourceColumn: survey_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column zendesk_user_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: 71857df4-bc06-40ad-8f77-7ad2d0d594ce
		summarizeBy: none
		sourceColumn: zendesk_user_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column zendesk_organization_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: b34560a4-3674-4dfb-af19-8c3c07514e56
		summarizeBy: none
		sourceColumn: zendesk_organization_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column enterprise_account_id
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Foreign Keys
		lineageTag: c7394511-6703-4a84-866e-3535f1667257
		summarizeBy: none
		sourceColumn: enterprise_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column parent_account_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 9d2b185c-5cce-479f-a728-b1a17e14b50e
		summarizeBy: none
		sourceColumn: parent_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column salesforce_account_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 9dcf6d34-6428-4d82-8101-77e83c707d98
		summarizeBy: none
		sourceColumn: salesforce_account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column team_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 212b32b8-b784-4fdc-92bc-047acce3c6df
		summarizeBy: none
		sourceColumn: team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column standardized_category_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 08af4ee2-5fec-4507-bd24-def70a9af705
		summarizeBy: none
		sourceColumn: standardized_category_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column squad_id
		dataType: string
		isHidden
		displayFolder: Foreign Keys
		lineageTag: 444b10bd-9471-46e2-8880-e04c1e56ab03
		summarizeBy: none
		sourceColumn: squad_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column ticket_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8088483-15a6-4c97-80d2-dde753a4c5f2
		summarizeBy: none
		sourceColumn: ticket_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","MARK_PRIMARY_KEYS"]}

	column 'Survey Created At'
		dataType: dateTime
		formatString: General Date
		lineageTag: 32ec7344-fbd6-4bc8-8d44-f5e27d507182
		summarizeBy: none
		sourceColumn: Survey Created At

		annotation SummarizationSetBy = Automatic

	column 'Survey Created Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 58c87b4e-8a56-4ab4-bc5e-0f8e2df3df3f
		summarizeBy: none
		sourceColumn: Survey Created Date

		annotation SummarizationSetBy = Automatic

	column 'Response At'
		dataType: dateTime
		formatString: General Date
		lineageTag: af349de3-ab1a-4a5c-b5a9-3e7a7665082a
		summarizeBy: none
		sourceColumn: Response At

		annotation SummarizationSetBy = Automatic

	column 'Response Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ee2f70d-983e-4c78-8c63-4365b3d819e1
		summarizeBy: none
		sourceColumn: Response Date

		annotation SummarizationSetBy = Automatic

	column 'Survey Sent At'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c6e7dfd-4c44-49cf-b645-5938beca77fb
		summarizeBy: none
		sourceColumn: Survey Sent At

		annotation SummarizationSetBy = Automatic

	column 'Survey Sent Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04bac148-bc1d-4fb6-ab0e-e6ce632789b4
		summarizeBy: none
		sourceColumn: Survey Sent Date

		annotation SummarizationSetBy = Automatic

	column 'Expires on Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 88796ceb-cba7-431f-be87-4fd90c7f3798
		summarizeBy: none
		sourceColumn: Expires on Date

		annotation SummarizationSetBy = Automatic

	column 'Experience CSAT'
		dataType: int64
		formatString: 0
		lineageTag: 0a8cac15-497f-4ea4-bfe8-cafe8638811e
		summarizeBy: none
		sourceColumn: Experience CSAT

		annotation SummarizationSetBy = Automatic

	column 'Reason for Key Metrics Score'
		dataType: string
		lineageTag: 956a4a8e-0043-4e6d-878c-6647da095588
		summarizeBy: none
		sourceColumn: Reason for Key Metrics Score

		annotation SummarizationSetBy = Automatic

	column 'Engineer CSAT'
		dataType: int64
		formatString: 0
		lineageTag: 6bfcf443-0547-4b17-989f-cf78e52bc6bb
		summarizeBy: none
		sourceColumn: Engineer CSAT

		annotation SummarizationSetBy = Automatic

	column 'Understanding Needs'
		dataType: int64
		formatString: 0
		lineageTag: e02c4931-dfd7-46fe-9842-d99e4cf315eb
		summarizeBy: none
		sourceColumn: Understanding Needs

		annotation SummarizationSetBy = Automatic

	column 'Agent Knowledge'
		dataType: int64
		formatString: 0
		lineageTag: d3671250-242e-4843-a28b-b20be882d5f6
		summarizeBy: none
		sourceColumn: Agent Knowledge

		annotation SummarizationSetBy = Automatic

	column 'Communicating Clearly'
		dataType: int64
		formatString: 0
		lineageTag: e3af580a-3c72-4a4e-b018-9ed5d5942d97
		summarizeBy: none
		sourceColumn: Communicating Clearly

		annotation SummarizationSetBy = Automatic

	column Friendliness
		dataType: int64
		formatString: 0
		lineageTag: 759f48f3-c382-40d6-835f-16f212201075
		summarizeBy: none
		sourceColumn: Friendliness

		annotation SummarizationSetBy = Automatic

	column Timeliness
		dataType: int64
		formatString: 0
		lineageTag: c031ee94-4a2b-4a90-b648-b48d45832480
		summarizeBy: none
		sourceColumn: Timeliness

		annotation SummarizationSetBy = Automatic

	column 'Customer Effort'
		dataType: int64
		formatString: 0
		lineageTag: e67631c2-b04d-47bb-9dfe-3e27b87c3f9b
		summarizeBy: none
		sourceColumn: Customer Effort

		annotation SummarizationSetBy = Automatic

	column 'Inquiry Resolved'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 009d471c-f16a-4c0b-a05d-551bfdcfd4d1
		summarizeBy: none
		sourceColumn: Inquiry Resolved

		annotation SummarizationSetBy = Automatic

	column 'Alert Close At'
		dataType: dateTime
		formatString: General Date
		lineageTag: d72dd688-286c-4ae8-811a-ed4a05fc4fde
		summarizeBy: none
		sourceColumn: Alert Close At

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh At'
		dataType: dateTime
		formatString: General Date
		lineageTag: acfefa60-6043-47c4-bc64-dd672ebf3cf0
		summarizeBy: none
		sourceColumn: Last Refresh At

		annotation SummarizationSetBy = Automatic

	partition FactTicketCsatSurvey-c82ce844-c658-49d6-acb2-d171cbb1d531 = m
		mode: import
		source =
				let
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "database(""service_cs_analytics"").supportv3_ticket_csat_survey_fact#(lf)| where is_support_team == ""TRUE""#(lf)    and is_support_squad == ""TRUE""#(lf)    and is_ticket_within_two_years == ""TRUE""#(lf)| distinct survey_id,#(lf)    ticket_id,#(lf)    zendesk_user_id,#(lf)    zendesk_organization_id,#(lf)    enterprise_account_id,#(lf)    parent_account_id,#(lf)    salesforce_account_id,#(lf)    team_id,#(lf)    standardized_category_id,#(lf)    squad_id,#(lf)    [""Survey Created At""]=survey_created_at,#(lf)    [""Survey Created Date""]=survey_created_date,#(lf)    [""Response At""]=response_at,#(lf)    [""Response Date""]=response_date,#(lf)    [""Survey Sent At""]=survey_sent_at,#(lf)    [""Survey Sent Date""]=survey_sent_date,#(lf)    [""Expires on Date""]=expires_on_date,#(lf)    [""Experience CSAT""]=experience_csat,#(lf)    [""Reason for Key Metrics Score""]=reason_for_key_metrics_score,#(lf)    [""Engineer CSAT""]=engineer_csat,#(lf)    [""Understanding Needs""]=understanding_needs,#(lf)    [""Agent Knowledge""]=agent_knowledge,#(lf)    [""Communicating Clearly""]=communicating_clearly,#(lf)    [""Friendliness""]=friendliness,#(lf)    [""Timeliness""]=timeliness,#(lf)    [""Customer Effort""]=customer_effort,#(lf)    [""Inquiry Resolved""]=inquiry_resolved,#(lf)    [""Alert Close At""]=alert_close_at,#(lf)    [""Last Refresh At""]=dag_last_run_at", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Survey Created At", type datetime}, {"Survey Created Date", type datetime}, {"Response At", type datetime}, {"Survey Sent Date", type datetime}, {"Expires on Date", type datetime}, {"Alert Close At", type datetime}, {"Response Date", type datetime}, {"Survey Sent At", type datetime}, {"Last Refresh At", type datetimezone}})
				in
				    #"Changed Type"

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MINIMIZE_POWER_QUERY_TRANSFORMATIONS"]}

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE","OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

