table PremiumSupportFinancials
	lineageTag: b626cd50-a1cc-41aa-90b1-531f27e7c6cd

	measure 'ARR metric' = ```
			
			SUM ( PremiumSupportFinancials[ARR] )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1aec8bbb-41f9-4efe-87d9-193603d04f24

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'COGS metric' = ```
			
			SUM ( PremiumSupportFinancials[COGS] )
			
			```
		formatString: #,0
		lineageTag: 027b7195-691f-4fdf-a6eb-56b71d57ee9b

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure 'Gross Margin % metric' = ```
			
			SUM ( PremiumSupportFinancials[Gross Margin %] )
			
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 3ab51fff-6443-4ccb-acdc-5737c7b4be2e

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PERCENTAGE_FORMATTING"]}

	measure 'Gross Margin $$ metric' = ```
			
			SUM ( PremiumSupportFinancials[Gross Margin $$] )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b8c2452d-0993-46b9-9811-8063021c50f4

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure 'Net Revenue metric' = ```
			
			SUM ( PremiumSupportFinancials[Net revenue] )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e5fe8881-4449-4763-a7ac-b3f98c2a934a

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	measure Index = ```
			
			CALCULATE (
			    COUNTROWS ( PremiumSupportFinancials ),
			    FILTER (
			        ALLSELECTED ( PremiumSupportFinancials ),
			        PremiumSupportFinancials[Date] <= MAX ( ( PremiumSupportFinancials[Date] ) )
			    )
			)
			
			```
		formatString: #,0
		lineageTag: 354549f8-df3d-41bc-8db9-36e8a0f06865

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 1913a53d-8a1a-4383-9947-026995783db7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","DATECOLUMN_FORMATSTRING"]}

	column ARR
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: da43cf09-59db-49c5-b3d5-6d2f5de1e602
		summarizeBy: sum
		sourceColumn: ARR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Net revenue'
		dataType: int64
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f070a897-8476-4d80-aaff-af83e340f842
		summarizeBy: sum
		sourceColumn: Net revenue

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column COGS
		dataType: int64
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c33df1f3-1913-4777-be11-d8f8aed15093
		summarizeBy: sum
		sourceColumn: COGS

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Gross Margin $$'
		dataType: int64
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 75f2a17d-9559-4d26-819c-bc49c8f75d14
		summarizeBy: sum
		sourceColumn: Gross Margin $$

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Gross Margin %'
		dataType: double
		isHidden
		formatString: 0%;-0%;0%
		lineageTag: 26daf544-1cdd-4597-9d99-36568067705b
		summarizeBy: sum
		sourceColumn: Gross Margin %

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	partition PremiumSupportFinancials-743a041c-0a32-468f-bb0b-b2748c64d378 = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/19LFWgAeoSY2RGF1MWP9_M3H4keFdVS17CIfaYspggyk/export?format=xlsx"),
				    #"Premium Support Financials_Table" = Source{[name="Premium Support Financials",ItemKind="Table"]}[Data],
				    #"Transposed Table" = Table.Transpose(#"Premium Support Financials_Table"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"ARR", Int64.Type}, {"Net revenue", Int64.Type}, {"COGS", Int64.Type}, {"Gross Margin $$", Int64.Type}, {"Gross Margin %", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"", "_1", "_2", "Premium Score Card Data as from Power BI as of 5/10", "Date_3", "ARR_4", "Net revenue_5", "COGS_6", "Gross Margin $$_7", "Gross Margin %_8", "_9", "Variance between Looker and Power BI Data", "Date_10", "ARR_11", "Net revenue_12", "COGS_13", "Gross Margin $$_14", "Gross Margin %_15"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Gross Margin %", Percentage.Type}, {"Gross Margin $$", Currency.Type}, {"COGS", Currency.Type}, {"Net revenue", Currency.Type}, {"ARR", Currency.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

