table ProductPillars
	lineageTag: fe7ce8c0-e192-4c07-a961-0b5116bb6cb0

	column 'Product Pillar'
		dataType: string
		lineageTag: 4e7f657c-a3da-496e-823a-3fb215aec128
		summarizeBy: none
		sourceColumn: Product Pillar

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Feature
		dataType: string
		lineageTag: b8c612a8-1ab9-4e1a-9101-a86a8f1ee796
		summarizeBy: none
		sourceColumn: Feature

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Metric
		dataType: string
		lineageTag: 5d655044-2b17-406b-b9ca-fababdb23307
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Actuals
		dataType: double
		lineageTag: 29e00c9e-8544-414a-a467-f9e5159aec8b
		summarizeBy: sum
		sourceColumn: Actuals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Base
		dataType: double
		lineageTag: 9ad4a617-cc30-4e73-87bc-2d31537c9d0b
		summarizeBy: sum
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Target
		dataType: double
		lineageTag: cc5146e0-79b0-471d-9c4f-b06647d0c0e0
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Weight
		dataType: double
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 9534d172-a4b9-41dc-8df1-0b0f33617d1b
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Index Points'
		dataType: double
		lineageTag: d24873ce-a635-4bce-ad7e-c462eb4599cd
		summarizeBy: sum
		sourceColumn: Index Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Weighted Index Points'
		dataType: double
		lineageTag: bd37417e-34e2-42ab-8aac-7d18a60ed127
		summarizeBy: sum
		sourceColumn: Weighted Index Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	partition ProductPillars = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk5NLi3KLKlUCCjKTylNLilW0lFySS1IzUtJTMovAXI8gxQ8MtMzgCwDPQswaQkhTcGUEZA0NAMSxkBmrA4RBjoHO4YgmWMBMcfSAG4cmEXArNS85EoF96LEggyIE0OL0lPzSrAYS76pzokFiclAZWATDEDG6RroGUIoA4TnjfQMjcEcE4j/oYZmlkG0OucXZOYg+9tEzxRMGsPZKO6LBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Product Pillar" = _t, Feature = _t, Metric = _t, Actuals = _t, Base = _t, Target = _t, Weight = _t, #"Index Points" = _t, #"Weighted Index Points" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product Pillar", type text}, {"Feature", type text}, {"Metric", type text}, {"Actuals", type number}, {"Base", type number}, {"Target", type number}, {"Weight", type number}, {"Index Points", type number}, {"Weighted Index Points", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS","OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

