table 'SHI Metrics V2'
	lineageTag: 2a24398c-454b-4312-a477-285517cd30b9

	column Dimension
		dataType: string
		lineageTag: 9da326bf-1e1c-4359-bf6c-e4a4851a16a1
		summarizeBy: none
		sourceColumn: Dimension

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Dimension ID'
		dataType: string
		lineageTag: 36d23429-b2db-4aa5-b449-281b1c8561ea
		summarizeBy: none
		sourceColumn: Dimension ID

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column 'Dimension Value'
		dataType: string
		lineageTag: 1b871417-459f-4bb0-b2e2-320e6e7143b5
		summarizeBy: none
		sourceColumn: Dimension Value

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Metric
		dataType: string
		lineageTag: 5af41c8e-655e-40f4-901c-e5f2087362a4
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column Weight
		dataType: double
		lineageTag: 70596b8d-0917-4f03-8965-85364392861d
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	column Base
		dataType: double
		lineageTag: e236e40a-334e-4d46-b097-9032986d38e9
		summarizeBy: sum
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	column Target
		dataType: double
		lineageTag: f0e9e6b3-b214-4946-92e7-07535613aa23
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	partition 'SHI Metrics V2' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Support%20Health%20Index%20Phase%203.xlsx"), null, true),
				    #"SHI Metrics_Sheet" = Source{[Item="SHI Metrics",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"SHI Metrics_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Dimension", type text}, {"Dimension ID", type text}, {"Dimension Value", type text}, {"Metric", type text}, {"Weight", type number}, {"Base", type number}, {"Target", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

