table SHITeamWeight
	excludeFromModelRefresh
	lineageTag: 9192cdf8-106a-440c-8af6-14d17dbfccd2

	column 'Team ID'
		dataType: string
		lineageTag: 26963a10-c1a2-478b-b5a3-a1e36272416e
		summarizeBy: none
		sourceColumn: Team ID

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","MARK_PRIMARY_KEYS"]}

	column Team
		dataType: string
		lineageTag: 008dfce2-0c6f-4b85-acbd-b01e0728f858
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Team Weight'
		dataType: double
		lineageTag: 06a4a0d8-c95e-4c4d-9b0f-d225b73fb689
		summarizeBy: sum
		sourceColumn: Team Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS"]}

	partition SHITeamWeight-7594f3fe-159d-4a73-a2f9-d9b0a9923fd4 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Support%20Health%20Index%20W_%20time%20to%20Resolved%20normalized.xlsx"), null, true),
				    #"SHI Team Weight_Sheet" = Source{[Item="SHI Team Weight",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"SHI Team Weight_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Team ID", type text}, {"Team", type text}, {"Team Weight", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

