table SHITeamMetrics
	excludeFromModelRefresh
	lineageTag: 296cf167-08b0-4e65-b920-edc8951a0cb1

	column 'Team ID'
		dataType: string
		lineageTag: ddeec43e-bb35-4a69-b959-6d16fb59596e
		summarizeBy: none
		sourceColumn: Team ID

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column Team
		dataType: string
		lineageTag: 22b865fb-e255-4b80-9a4b-04439ea60b9d
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","REMOVE_REDUNDANT_COLUMNS_IN_RELATED_TABLES"]}

	column 'Metric '
		dataType: string
		lineageTag: 91826a7f-e24f-47ce-9c32-74b8e6108b89
		summarizeBy: none
		sourceColumn: "Metric "

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","TRIM_OBJECT_NAMES","OBJECTS_SHOULD_NOT_START_OR_END_WITH_A_SPACE","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column 'Weight '
		dataType: double
		formatString: 0
		lineageTag: f96d6b10-e828-4485-92f3-ab97d0ac274d
		summarizeBy: sum
		sourceColumn: "Weight "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","TRIM_OBJECT_NAMES","OBJECTS_SHOULD_NOT_START_OR_END_WITH_A_SPACE","NUMERIC_COLUMN_SUMMARIZE_BY","HIDE_FACT_TABLE_COLUMNS"]}

	column Base
		dataType: double
		lineageTag: 08075f3d-3fc5-4d05-8f78-b8192f38bd48
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS"]}

	column Target
		dataType: double
		lineageTag: 4a9c8b43-9028-41d7-aea2-d1b012961854
		summarizeBy: none
		sourceColumn: Target

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS"]}

	partition SHITeamMetrics-30e54956-8865-4bdd-9a12-6cf0971327d7 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://githubazure.sharepoint.com/sites/cs-analytics/Shared%20Documents/CS%20Analytics%20Artifacts/Fabric%20Code%20Repository/Excel%20Config%20Files/Support%20Health%20Index%20W_%20time%20to%20Resolved%20normalized.xlsx"), null, true),
				    #"SHI Team Metrics DEV_Sheet" = Source{[Item="SHI Team Metrics DEV",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"SHI Team Metrics DEV_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Team ID", type text}, {"Team", type text}, {"Metric ", type text}, {"Weight ", Percentage.Type}, {"Base", type number}, {"Target", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column7", "Old Weight ", "Column9", "Column10", "Column11"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([#"Metric "] <> "Escalation IR % Sev2 ") and ([Team] <> null and [Team] <> ""))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","PARTITION_NAME_SHOULD_MATCH_TABLE_NAME_FOR_SINGLE_PARTITION_TABLES"]}

	annotation PBI_NavigationStepName = Navigation

