table SquadTeamBridge
	excludeFromModelRefresh
	lineageTag: 00f6b7ef-1079-46ad-8839-fdabd2630835

	column Squad
		dataType: string
		lineageTag: 2b99f833-5d79-4e74-9f08-02704704fd9c
		summarizeBy: none
		sourceColumn: Squad

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Team
		dataType: string
		lineageTag: 4bf24c92-0ab3-4ed7-a78b-69614d05351a
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	partition SquadTeamBridge = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jY5Bi8IwEIX/SsjZg3jY+yo9eJPtgofqIcRxN2w6KZMZwX9voYgdpgvewvte5ntd5z9jLILsWohCie9+5Z9Pd5L1evPhvuAGKOBaGYZC7M+rzm9Tzgl/3mzvSj/kFDDCmx/GVVDrWG6QgQZKFXR+IOiT9O6QpS6TlgNeAl00/Yb4iymGPO3a7KxjCo1Ax+r6hPTpJpZ6rwy9FcyR0SxBJZsXtPJY6I8B2RpnxAgXmPLNuNbt8UqhMklkIbBSw43638ZrwPkB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Squad = _t, Team = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Squad", type text}, {"Team", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

