table Table
	lineageTag: e57343d5-87b7-414e-a282-843f5b2c906f

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: a72641ae-0727-48b5-8ff2-1f01621583ae
		summarizeBy: sum
		sourceColumn: Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Range
		dataType: string
		lineageTag: 9e0d14e0-5357-4205-b5bb-79e0b050301b
		summarizeBy: none
		sourceColumn: Range
		sortByColumn: Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 58529b70-ff6b-407e-a5b9-a3cf05cb917d
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VZFLCsMwDESvYrwORfI3vkNvELIItNAu2kKTLHr7WnZsKQYZo6cZBnma9HVZN2XUbfmtetAm16jn4ejb1re5Evdj68dcCEIAXQGEDCN0DaGjCxmFrgpFZRmljhJUKRuOneUn3V4ECb4nCZ5gEPE5Zqw5o7CF1KX0LvYCe/V6vvftThwugOAwHIdGT7s4TRoYbTtl1eypHp/9W6fYrfhZ+Rk0Vc3QUC6xjCBgYWIXaAQkJlZhXGdY/nOe/w==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Range = _t, Value = _t, Rank = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Range", type text}, {"Value", type number}, {"Rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

