table TeamSquadTicketMapping
	lineageTag: 69515e8b-3bac-43a8-92c2-d18a886e2026

	measure 'Measure 6' = SELECTEDVALUE(TeamSquadTicketMapping[Team Assigned])&" - "&SELECTEDVALUE(DimSquad[Squad])
		lineageTag: f2936c22-d5d2-4bf0-a101-4334b9c5edf2

	column ticket_id
		dataType: int64
		formatString: 0
		lineageTag: bbf3136e-22a7-4b36-aa9c-680f4148eadc
		summarizeBy: count
		sourceColumn: ticket_id

		annotation SummarizationSetBy = User

	column 'Team Assigned'
		dataType: string
		lineageTag: 278708c8-6bdb-4eac-b99c-864448379764
		summarizeBy: none
		sourceColumn: Team Assigned

		annotation SummarizationSetBy = Automatic

	column 'Team Solved'
		dataType: string
		lineageTag: 4ff25aab-b2c3-43b5-9e2e-1ffb23edff2a
		summarizeBy: none
		sourceColumn: Team Solved

		annotation SummarizationSetBy = Automatic

	column 'Squad Assigned'
		dataType: string
		lineageTag: b67f240b-1aa5-4316-a008-41a4e7fc4a2b
		summarizeBy: none
		sourceColumn: Squad Assigned

		annotation SummarizationSetBy = Automatic

	column 'Squad Solved'
		dataType: string
		lineageTag: 49d5eb40-a50a-4247-bfa0-bfd7313cb716
		summarizeBy: none
		sourceColumn: Squad Solved

		annotation SummarizationSetBy = Automatic

	column 'Team / Squad' = TeamSquadTicketMapping[Team Assigned]&" - " &TeamSquadTicketMapping[Squad Assigned]
		lineageTag: 09185f74-3c2f-4395-a399-0321e9f37e97
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 846221ad-62a0-4599-91dd-bd24acb9e4d5
		summarizeBy: none
		sourceColumn: Created Date

		annotation SummarizationSetBy = Automatic

	column 'Solved Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05835281-ce4d-4cd6-9512-c5212b192b34
		summarizeBy: none
		sourceColumn: Solved Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition TeamSquadTicketMapping = m
		mode: import
		source = ```
				let 
				
				    Source = AzureDataExplorer.Contents("gh-analytics.eastus.kusto.windows.net", "service_cs_analytics", "let manager_info = #(lf)    database(""service_cs_analytics"").supportv3_agent_manager_fact#(lf)    | join kind=leftouter (#(lf)        database(""service_cs_analytics"").supportv3_user_dim#(lf)        | project manager_zendesk_user_id = zendesk_user_id, manager_name = name#(lf)    ) on manager_zendesk_user_id#(lf)    | project manager_zendesk_user_id, agent_dotcom_id, manager_name;#(lf)let dim_assignee = #(lf)database(""service_cs_analytics"").supportv3_user_dim#(lf)| join kind=inner (#(lf)    database(""service_cs_analytics"").supportv3_ticket_fact#(lf)    | project assignee_zendesk_id, is_support_team, is_support_squad, is_ticket_within_two_years#(lf)) on $left.zendesk_user_id == $right.assignee_zendesk_id#(lf)| join kind=inner (#(lf)    database(""data_operations"").org_hierarchy#(lf)    | project hubber_dotcom_id, worker_type, cost_center_name, contingent_worker_type, hubber_name#(lf)) on $left.dotcom_id == $right.hubber_dotcom_id#(lf)| join kind=leftouter (#(lf)    manager_info#(lf)) on $left.dotcom_id == $right.agent_dotcom_id#(lf)    | where is_support_team == ""TRUE""#(lf)        and is_support_squad == ""TRUE""#(lf)        and is_ticket_within_two_years == ""TRUE""#(lf)        and isnotempty(zendesk_user_id) and isnotempty(dotcom_id)#(lf)| distinct zendesk_user_id, name, cost_center_name, current_assigned_squad_1;#(lf)let base_data =#(lf)    database(""service_cs_analytics"").supportv3_ticket_fact#(lf)    | where is_support_team == ""TRUE""#(lf)        and is_support_squad == ""TRUE""#(lf)        and is_ticket_within_two_years == ""TRUE""#(lf)    | join kind=leftouter (#(lf)        database(""service_cs_analytics"").supportv3_team_dim#(lf)        | project team_affiliated_id, team#(lf)    ) on team_affiliated_id#(lf)    | join kind=leftouter (#(lf)        dim_assignee#(lf)    ) on $left.assignee_zendesk_id == $right.zendesk_user_id#(lf)    | join kind=leftouter (#(lf)        database(""service_cs_analytics"").supportv3_squad_dim#(lf)        | project squad_id, squad#(lf)    ) on squad_id#(lf)    // Step-by-step logic for cost center team name#(lf)    | extend cost_name = trim("" "", toupper(cost_center_name))#(lf)    | extend team_solved =#(lf)        iff(cost_name startswith  ""ENTERPRISE"", ""Enterprise"",#(lf)        iff(cost_name startswith  ""PREMIUM PLUS"", ""Premium Plus"",#(lf)        iff(cost_name startswith ""SECURITY & REVENUE"", ""Security & Revenue Support"",#(lf)        iff(cost_name startswith ""TECHNICAL"", ""Technical"", ""N/A""))))#(lf)    | extend squad_solved = iff(isempty(current_assigned_squad_1), "" "", current_assigned_squad_1)#(lf)    | extend team_assigned = team, squad_assigned = squad;#(lf)base_data#(lf)| project#(lf)    ticket_id,#(lf)    [""Team Assigned""] = team_assigned,#(lf)    [""Squad Assigned""] = squad_assigned,#(lf)    [""Squad Solved""] = squad_solved,#(lf)    [""Team Solved""] = team_solved,#(lf)    [""Created Date""] = created_date,#(lf)    [""Solved Date""] = solved_date", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]), 
				
				     #"Replaced Value" = Table.ReplaceValue(Source,"N/A","Others",Replacer.ReplaceText,{"Team Solved"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Created Date", type datetime}, {"Solved Date", type date}})
				in
				    #"Changed Type"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

