table TicketForecastforLatestForecastDate
	isHidden
	lineageTag: 2f2c4502-161a-4730-95c8-bfa3f6951ce3

	column Month
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: c2f33010-059a-4560-b9da-d12f0a5f9831
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Latest Forecast Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 5105d83f-5c50-4ab2-a684-93e66a780644
		summarizeBy: none
		sourceColumn: Latest Forecast Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition TicketForecastforLatestForecastDate = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(Lakehouse_Endpoint, "cs_analytics"),
				    dbo_ticket_forecast_output = Source{[Schema="dbo",Item="ticket_forecast_output"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_ticket_forecast_output,{"team", "squad", "region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"month_end", "Month"}, {"tickets_forecast", "Tickets Forecasted"}, {"forecast_run_date", "Forecast Run Date"}}),
				    #"Grouped Rows" = Table.Group(#"Renamed Columns", {"Month"}, {{"Latest Forecast Date", each List.Max([Forecast Run Date]), type nullable date}})
				in
				    #"Grouped Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

