table WorkdayHeadcounSummary
	lineageTag: 0e52a824-57cb-42e6-afd9-848a31d902e2

	column Month
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5fff56d9-b4aa-411d-8f80-0e3001f4df72
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS","MONTHCOLUMN_FORMATSTRING"]}

	column Data_Refresh_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7ce17875-7d29-49cc-9a17-aaccfb45ae85
		summarizeBy: none
		sourceColumn: Data_Refresh_Date

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","DATECOLUMN_FORMATSTRING"]}

	column Team
		dataType: string
		lineageTag: a4d8e765-6127-4912-92dd-6052733c33b7
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["REMOVE_REDUNDANT_COLUMNS_IN_RELATED_TABLES","OBJECTS_WITH_NO_DESCRIPTION"]}

	column 'Full Team'
		dataType: string
		lineageTag: 1d5e5b03-0e62-4d8e-a425-e06bd73b3669
		summarizeBy: none
		sourceColumn: Full Team

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Team_ID
		dataType: string
		isHidden
		lineageTag: f83cf797-8d63-4366-b703-2c15c60e5e9a
		summarizeBy: none
		sourceColumn: Team_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION","RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE","HIDE_FOREIGN_KEYS"]}

	column Squad
		dataType: string
		lineageTag: f4f39562-e81b-42d9-9be7-b41274d09dd3
		summarizeBy: none
		sourceColumn: Squad

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Squad_ID
		dataType: string
		isHidden
		lineageTag: 368dacd5-1094-4ba1-8d14-406eeb5433f3
		summarizeBy: none
		sourceColumn: Squad_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Region
		dataType: string
		lineageTag: 27abfbf4-b1f0-408c-b3b5-4c18048eff5b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Region_ID
		dataType: string
		isHidden
		lineageTag: 22e0262f-8de8-498c-9d3c-eb75395bb3bc
		summarizeBy: none
		sourceColumn: Region_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	column Headcount
		dataType: double
		lineageTag: 430c56aa-dc16-4910-8292-2bd8ab04948c
		summarizeBy: sum
		sourceColumn: Headcount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Ramped_Capacity
		dataType: double
		lineageTag: f78a5bdc-ea91-4745-8195-ac9cfc7a58f0
		summarizeBy: sum
		sourceColumn: Ramped_Capacity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","HIDE_FACT_TABLE_COLUMNS","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column New_Hire
		dataType: double
		lineageTag: 9f01327e-6bad-412c-84f2-c722ca492578
		summarizeBy: sum
		sourceColumn: New_Hire

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column 'Long Leaves'
		dataType: double
		lineageTag: 8c9dbfeb-371b-47d2-9bba-e28568de94c7
		summarizeBy: sum
		sourceColumn: Long Leaves

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["AVOID_FLOATING_POINT_DATA_TYPES","OBJECTS_WITH_NO_DESCRIPTION","NUMERIC_COLUMN_SUMMARIZE_BY"]}

	column Ramped_Capacity_new_hires
		dataType: double
		lineageTag: 88b9726f-8551-4713-9460-77402a56d96a
		summarizeBy: sum
		sourceColumn: Ramped_Capacity_new_hires

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ramped_Capacity_onboarded
		dataType: double
		lineageTag: 92b79114-e616-404b-99c5-46260109f65c
		summarizeBy: sum
		sourceColumn: Ramped_Capacity_onboarded

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition WorkdayHeadcounSummary = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"eaaa1a58-9552-4a94-accd-a9798f7a25e7" = Workspaces{[workspaceId="eaaa1a58-9552-4a94-accd-a9798f7a25e7"]}[Data],
				    #"9179fa10-70e7-486d-b218-a1cdd9aeaeb3" = #"eaaa1a58-9552-4a94-accd-a9798f7a25e7"{[dataflowId="9179fa10-70e7-486d-b218-a1cdd9aeaeb3"]}[Data],
				    #"Workday Headcount Summary_" = #"9179fa10-70e7-486d-b218-a1cdd9aeaeb3"{[entity="Workday Headcount Summary",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Workday Headcount Summary_",{{"Full_Team", "Full Team"}, {"Long_Leaves", "Long Leaves"}, {"Ramped_Capacity", "Ramped_Capacity"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	annotation PBI_NavigationStepName = Navigation

