table Announcements
	lineageTag: 4616d3ea-073e-4198-bb7f-973f4b4a0d28

	column Model
		dataType: string
		lineageTag: 2de64925-5425-439b-9d2b-8fe7af4efcf8
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7e30fb96-605b-4ef4-b932-9087685ce3a1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: b66f5647-dd91-4afe-9917-74a7eafdb6f9
			defaultHierarchy: LocalDateTable_5f2148fe-abff-4360-a813-b6a61c965309.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Announcements
		dataType: string
		lineageTag: 38692704-87df-416e-9269-e14273cdd2cc
		summarizeBy: none
		sourceColumn: Announcements

		annotation SummarizationSetBy = Automatic

	partition Announcements-c02310c0-325e-479d-8ed5-27d5fd77337b = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Gv1eYZKJCkXVA8X_HkGoUpiPtUARNHRfDyzqY228Tfc/edit#gid=1242546551"),
				    Announcements_Table = Source{[name="Announcements",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Announcements_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Model", type text}, {"Date", type date}, {"Announcements", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

